### ISSUE TITLE
Add mod item physics

### ISSUE THREAD

**Issue by ScorpioneOrzion** [ChosenArchitect/Project-Architect#1]
item physics, to yeet your items away (this is more or less just as a joke)
https://www.curseforge.com/minecraft/mc-mods/itemphysic

**Comment by ChosenArchitect** [comment]
You can add this mod yourself but I don't really want to add to the mod list at this point as its already large.

**Comment by ScorpioneOrzion** [comment]
I see, also it was just for fun.
