### ISSUE TITLE
Problem with peaceful mob loot and EMC

### ISSUE THREAD

**Issue by Nephrium** [ChosenArchitect/Project-Architect#10]
It claims that things like wool and leather have EMC, and it accepts them but the items don't show up in the list . I saw you specifically use the tablet and stuff to make a bed in the first episode of the LP, but when I went to try and do the same thing, I couldn't access those items. Tried it again, even put in a dyed wool but I couldn't pull that out either.

**Comment by ChosenArchitect** [comment]
Do you have enough EMC to exchange the items?

**Comment by Nephrium** [comment]
Yes, if you put the wool, leather, or even animal meat in there it just sort of gives you the EMC, but isn't on the list to be pulled back out.

**Comment by ChosenArchitect** [comment]
Can you post a screenshot of your EMC table

**Comment by Nephrium** [comment]
Well, never mind I figured out the problem. The circle in the middle that you can use to learn something with out actually putting in? I had the wooden pick ax I'd made in that slot and apparently there is some glitch that when something in sitting in that space some of the search items won't show up. The moment I removed it the wool showed up . Pictures showing what I mean attached... so it's solved pretty much, but still a weird glitch
![Pick, wool search, no wool EMC](https://user-images.githubusercontent.com/24380538/152312989-5c3f6253-ea9f-4d8e-8402-641d53606ed1.png)
![Wool found in EMC!!!!](https://user-images.githubusercontent.com/24380538/152313062-754cf9d5-6b62-4219-992e-f7a2d9cf4b3f.png)

**Comment by fuelhauler** [comment]
Remove the Pickaxe from the center slot of the table

**Comment by ChosenArchitect** [comment]
That's what I thought the issue might be but you never know! Thanks for responding!
