### ISSUE TITLE
Crash when starting minecraft

### ISSUE THREAD

**Issue by mydayyyyy** [ChosenArchitect/Project-Architect#100]
**Describe the bug**
-> Crash when i load minecraft.

**To Reproduce**
1.  Only start Minecraft with the mods
2. 
3. 
4. 

**Expected behavior**
-> Minecraft start

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> Minecraft 1.16.5
**Java Version**
-> CurseForge integrated
**Modpack Launcher Used**
-> CurseForge
**Ram Allocated**
-> 170000

**Additional context**
-> Screenshots

**Comment by mydayyyyy** [comment]
Crash:
[crash-2022-02-19_08.55.53-fml.txt](https://github.com/ChosenArchitect/Project-Architect/files/8101673/crash-2022-02-19_08.55.53-fml.txt)

Latest Log:
[latest.log](https://github.com/ChosenArchitect/Project-Architect/files/8101674/latest.log)

**Comment by mydayyyyy** [comment]
![1](https://user-images.githubusercontent.com/100017086/154792558-0f0b145f-e5b6-4133-ae84-f375b15773fa.jpg)

**Comment by mydayyyyy** [comment]
![2](https://user-images.githubusercontent.com/100017086/154792585-d41bfb2d-5ef2-4bc8-970f-6f3b642dcc62.jpg)

**Comment by mydayyyyy** [comment]
I try a fresh new Minecraft with only the mod and Project E. I get the same Error as in the screenshot.

crashlog:
[crash-2022-02-19_09.07.26-fml.txt](https://github.com/ChosenArchitect/Project-Architect/files/8101688/crash-2022-02-19_09.07.26-fml.txt)

Latest Log:
[latest.log](https://github.com/ChosenArchitect/Project-Architect/files/8101689/latest.log)

**Comment by smmailik** [comment]
I can recomend you to install GDLauncher it may help .. It's installing java and everything by itself and you will not have anymore headaches with modpacks ..
