### ISSUE TITLE
The end

### ISSUE THREAD

**Issue by OgPaine** [ChosenArchitect/Project-Architect#103]
Describe the bug
-> When re spawning the end dragon the towers the crystals are on re gen over the old towers 

To Reproduce

use end crystals to summon the dragon It didn't happen the first time or I didn't notice but summing the 2nd time 
->for them to not to re gen over the previous tower

Screenshots
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
https://imgur.com/a/yYI5BXc
Modpack version
-> 1.4
Java Version
->
Modpack Launcher Used
-> curseforge
Ram Allocated
-> 8G

Additional context
->

**Comment by James103** [comment]
I seem to be getting a similar error in version 1.7 of the mod pack, whereby doing the following may still cause towers to stack.

1. Create a new world.
2. Enter the End.
3. Kill the Ender Dragon.
4. Once the dragon dies and the exit end portal reopens, save and quit.
5. Re-open the world.
6. Respawn the Ender Dragon.
7. Notice that some of the towers have doubled in height.
8. Repeat steps 3-6.
9. Notice that some of the towers have tripled in height from what they originally were and that there are gaps in some of the towers.

Alternatively, a portion of @ChosenArchitect's video shows the issue described above ([click to watch](https://youtu.be/-Vo6-aRCp_4?t=1270)).
