### ISSUE TITLE
could u make normal glass pane emcble pls

### ISSUE THREAD

**Issue by Adi-Zeliger** [ChosenArchitect/Project-Architect#104]
**Is your feature request related to a problem? Please describe.**
->

**Describe the solution you'd like**
->

**Describe alternatives you've considered**
->

**Mod Sugestions**
->

**Additional context**
->

**Comment by HalJordan** [comment]
Look at the EMC of a glass block. You would have to make glass cost more, as well as sand and anything else where another mod lets you convert between them so it all matches(i.e. cobble stone can be ground to gravel, then to sand, then sand smelted to glass in most machinery mods like thermal) or you could dupe emc. The mod works off of 1 EMC being the absolute smallest amount. It's an integer, not a floating point.

If your'e looking to recycle the panes, you should be able melt the panes in a tinker's smeltery, then cast it back into blocks.
