### ISSUE TITLE
CTD when acquiring a new Morph

### ISSUE THREAD

**Issue by Flatts3000** [ChosenArchitect/Project-Architect#105]
**Describe the bug**
->
CTD when acquiring a new Morph

**To Reproduce**
1. Acquire a pig morph
2. Acquire a chicken morph

**Modpack version**
->
1.5

Crashlog: https://pastebin.com/bRVMFecV

This happened when I killed a chicken. Looking at the logs, it says it crashed when acquiring a pig morph, so I expect it was looking for the pig when killing the chicken, couldn't find it, and threw a NPE.

Crashlog 2: https://pastebin.com/QuTH53je

Happened again when killing a skeleton

**Comment by ChosenArchitect** [comment]
Remove Optfine and try again
