### ISSUE TITLE
Feral Flare Lantern/Big Reactor bug 

### ISSUE THREAD

**Issue by Winkiloves23** [ChosenArchitect/Project-Architect#106]
**Describe the bug**
->I don't know why but for some reason when i have a Feral Flare by my Bigger Reactor and load into my world my reactor acts like its incomplete like the light source that the lanterns admits effects it some how once i break it and break a reactor block and replace it down then it works again but if i don't break the lantern first nothing happens it still acts like its incomplete 

**To Reproduce**
1. Put a Feral flare lantern down by a bigger reactor 
2. let the flare do its thing and light up the area 
3. log out and log back in 
4. 

**Expected behavior**
->lights up the place and don't break my reactor

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
Not  a screenshot but i do have a video showing whats happening and why i believe its messing with the reactor for some reason - https://www.youtube.com/watch?v=5UgBZUghEFw
**Modpack version**
->1.5
**Java Version**
->jre-8u321-windows x64
**Modpack Launcher Used**
->Cursedforge
**Ram Allocated**
->7G

**Additional context**
-I don't know if this happens 100% of the time

**Comment by jpwanabe** [comment]
Add coolant(water) into the reactor in the air blocks to stop this from happening. Also makes the reactor produce more power. The lights spawn in the reactor and breaks it.
