### ISSUE TITLE
Please consider adding this mod

### ISSUE THREAD

**Issue by Winkiloves23** [ChosenArchitect/Project-Architect#107]
**Is your feature request related to a problem? Please describe.**
->

**Describe the solution you'd like**
->

**Describe alternatives you've considered**
->

**Mod Sugestions**
->RfInfinitybooster for Refined Storage 

**Additional context**
->It sucks adding more of the transmitters and receivers around you base or world since the max range for refined storage is only 48 blocks i would like to see this to be added to project architect since it will give you infinite range throughout your world and interdimensional access to your storage for the cost of around 12,00 rf a tick 4,000 for the range upgrade 8,000 for the dimensional they do have emc of 338,310 for the range booster and 1,911,416 emc for the dimension card

**Comment by ChosenArchitect** [comment]
Mod has been added!
