### ISSUE TITLE
SERVER 

### ISSUE THREAD

**Issue by cjonsey97** [ChosenArchitect/Project-Architect#11]
**Is your feature request related to a problem? Please describe.**
->can you add a server pack

**Describe the solution you'd like**
->

**Describe alternatives you've considered**
->

**Mod Sugestions**
->

**Additional context**
->

**Comment by ChosenArchitect** [comment]
Server pack will be available once its out of BETA.

**Comment by cjonsey97** [comment]
thank you so much  and love your content

**Comment by joldfield101** [comment]
I managed to get a server up and running. Hit me up on the discord if you want. Basically get a "vanilla" forge server setup and then copy in the files from the modpack.

**Comment by ChosenArchitect** [comment]
Server File Is UP
