### ISSUE TITLE
Cosmetic armor

### ISSUE THREAD

**Issue by jpwanabe** [ChosenArchitect/Project-Architect#110]
**Is your feature request related to a problem? Please describe.**
->It is nice to be able to wear the top level armor but not look like a tomato 

**Describe the solution you'd like**
->
Add this mod
https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked
**Describe alternatives you've considered**

**Mod Sugestions**
->
Cosmetic armor
https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked
**Additional context**
->

**Comment by ChosenArchitect** [comment]
Im going to add it in the next update

**Comment by jpwanabe** [comment]
Thanks man. We are running the pack for our community and everyone loves it.
