### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by J3FFXDME** [ChosenArchitect/Project-Architect#111]
**Opening the Universal Wireless grid causes a Memory leak**
When i was making a Universal Wireless grid it caused a memory leak

**To Reproduce**
Steps to reproduce the behavior: (im not 100% sure if its just me)
1. make a Universal Wireless Grid 
2. Open it (or put it in curios slot and use keybind)

**Expected behavior**
->idk what to put here

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->
**Java Version**
-> Version 8, update 321, build 1.8.0
**Modpack Launcher Used**
->Curse Forge
**Ram Allocated**
->10G

**Additional context**
->

**Comment by BaggedTaco** [comment]
I found that this issue involves the EMC Interface and the Wireless Universal Grid. If you remove the EMC interface from the RF system it seems to work fine. All of the normal RF Wireless Grids work fine as well.

**Comment by ChosenArchitect** [comment]
I have not seen the same issue with all my testing.
I will keep an eye on this however.

**Comment by starforcraft** [comment]
This error only happened on the server, should now be fixed in the new Version as I said in the other issue lol
