### ISSUE TITLE
Backpack doesnt show full inventory

### ISSUE THREAD

**Issue by Deadlite93** [ChosenArchitect/Project-Architect#113]
**Describe the bug**
->While in my back bauble slot, my netherite backpack is only showing inventory of about 3 lines{same size as player inventory} it works fine when i take it our of baubles and use the hotkey to open it from my player inventory.

**To Reproduce**
1. Wear Sophisticated backpack in bauble slot
2. use hotkey to open backpack
3. witness only a small bit of space
4. it replaces player inventory with the lines shown from the backpack.

**Expected behavior**
->when i open the bag, it should show me the normal menu right?

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![Screenshot (11)](https://user-images.githubusercontent.com/99531956/154992421-59c1efdc-30d1-409d-a423-6efd96d873aa.png)
![Screenshot (10)](https://user-images.githubusercontent.com/99531956/154992429-3613dd59-8c2a-40d5-969e-b7e1635a1ee1.png)

**Modpack version**
->1.5 and older(server hasnt updated to 1.6 yet)
**Java Version**
->1.16.5
**Modpack Launcher Used**
->curseforge
**Ram Allocated**
->6G

**Additional context**
->its happened on older versions, but it seems inconsistent

**Comment by ChosenArchitect** [comment]
make sure all key "B" conflicts are removed from your controls

**Comment by Deadlite93** [comment]
> make sure all key "B" conflicts are removed from your controls

I've made sure that was done, sorry for not saying that before. I still haven't been able to recreate the issue since the update to the most recent version. Thank you for your perseverance and awesome content.

**Comment by Deadlite93** [comment]
the issue does remain as it turns out. it started happening again to me and my friend today in our server. can just use backpack in inventory instead of baubles slot in the mean time
