### ISSUE TITLE
A mod that allows us to move or make Mob Spawners 

### ISSUE THREAD

**Issue by Winkiloves23** [ChosenArchitect/Project-Architect#117]
**Is your feature request related to a problem? Please describe.**
->I would like to see a mod in project architect that allows us to move mob spawners and be able to tell what spawners are where since atm the only way to move spawners is with empty sack but those do not tell you what spawner is inside it all it says is spawner 
**Describe the solution you'd like**
->Add a Mod that allows us to move the spawners easily or pick them up and have them placed into our inventories or be able to make them like in Draconic Evolutions 
**Describe alternatives you've considered**
->Any mod is fine i would prefer being able to make the Mob spawners like from Draconic evolution or a mod that simply allows us to pick up spawners while knowing what spawner it is 
**Mod Suggestions**
->Silktouch Spawners mod draconic evolution etc

**Additional context**
->I know you dont tactically make spawners in draconic evolution you turn broken spawners into stabilized spawners but i think you know what i mean as make

**Comment by snowlock-18** [comment]
The modpack does have such a mod - Apotheosis allows the collection of spawners with a silk-touch pickaxe at the cost of 100 durability to the pickaxe (and other ways to change the spawner eg. increasing spawn counts, spawn ranges, delays and much more).
Jump into Apotheosis' mod page for more info =)

**Comment by ChosenArchitect** [comment]
So there are many ways to move spawners in this modpack. One of the main ways is using a sack of holding...
