### ISSUE TITLE
Crashes When I Open Morph Interface On Server

### ISSUE THREAD

**Issue by TempusAnath** [ChosenArchitect/Project-Architect#119]
After entering the world, I click on the button to select the mob I want to turn into, and the game crashes. This problem does not exist if I play in single player mode. 

1. I start the server via startserver.bat 
2. I start the game 
3. I enter to the server
4. I open morph interface 

**Modpack version**
->1.6
**Java Version**
->1.8.0.321 (64 Bit)
**Modpack Launcher Used**
->CurseForge, Minecraft Launcher
**Ram Allocated**
->12GB

This problem occurs when playing both with magnesium or optifine, and without these mods.

[Crash with Magnesium.txt](https://github.com/ChosenArchitect/Project-Architect/files/8143322/Crash.with.Magnesium.txt)
[Crash with Optifine.txt](https://github.com/ChosenArchitect/Project-Architect/files/8143323/Crash.with.Optifine.txt)
[Crash without Magnesium or Optifine.txt](https://github.com/ChosenArchitect/Project-Architect/files/8143324/Crash.without.Magnesium.or.Optifine.txt)

**Comment by ChosenArchitect** [comment]
Cant reproduce and crash log doesn't give any info
