### ISSUE TITLE
Cannot Load 3 mods

### ISSUE THREAD

**Issue by WitchCandy** [ChosenArchitect/Project-Architect#12]
**Describe the bug**
-> whenever I try to open it, there seems to be errors loading 3 mods. Those mods are Better Nether Reforged, Portality, and Titanium.

**To Reproduce**
1.  open the game
2. let it load
3. errors pop up

**Expected behavior**
-> I expected to be able to open the game and play

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image](https://user-images.githubusercontent.com/98929777/152270132-608fdd1e-3060-4e07-a743-1f2fb2d3c0b1.png)

**Modpack version**
-> 1.1
**Java Version**
-> 1.8.0_51
**Modpack Launcher Used**
-> CurseForge (the app)
**Ram Allocated**
-> 7-8GB

**Additional context**
-> I may have a lower end PC, but it can run Roguelike Adventures and Dungeons just fine, and that modpack has even more mods. It can also run Crucial 2 and Levitated

**Comment by jstansel** [comment]
What comes after "Not enough" in the error messages?

You have an ancient version of Java 8 and I recommend to upgrade as a matter of principle but I doubt it would solve this issue.

**Comment by WitchCandy** [comment]
I realize it wasnt full screen so things were cut off, so sorry! heres the full screen

![image](https://user-images.githubusercontent.com/98929777/152276605-2fc2c252-f63b-433b-9ded-67c1ad7926e6.png)

**Comment by ChosenArchitect** [comment]
Did you only try and load the pack once? Did you try and reinstall the modpack?

**Comment by WitchCandy** [comment]
I did load it a couple times yes, however I really hadn’t thought of reinstalling personally. I’ll try that and possibly update if that has worked! Thanks chosen

**Comment by fuelhauler** [comment]
If you are using MultiMC ( and I assume other launchers besides Curseforge) switch to Forge 36.2.25

**Comment by jwwright520** [comment]
I had the same issue... I switched to forge 36.2.25 and down-graded my java version to Java 8u311 and it works fine. I'm using the MultiMC launcher.

**Comment by HalJordan** [comment]
I'm getting a similar error with PolyMC(bastard child of MultiMC), mine's not even giving that info, just two identical generic lines about mod not loading(no mod name). I've tried reinstalling, tried with 1.1 and 1.0. But this is from the Curseforge Instance setup. I'm trying now straight from the curseforge zip so can't make any changes, if that doesn't work, I'll see what forge/java versions are in use.

Edit: Yeah, it was Java. For some reason PolyMC was defaulting to 1.17
