### ISSUE TITLE
Updated Server to v1.6 Mod Mismatch Error

### ISSUE THREAD

**Issue by Nite-Hare** [ChosenArchitect/Project-Architect#120]
**Describe the bug**
Cannot join server because I get an error that says "Connection Closed - mismatched mod channel list"
->

**To Reproduce**
1. Update server files from v1.3 to v1.6
2. Play using Curse Forge and receive this message "Connection Closed - mismatched mod channel list"
3. 
4. 

**Expected behavior**
Join game and be able to play just as in v1.3
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->1.6
**Java Version**
->version 8 update 291
**Modpack Launcher Used**
->Curse Forge
**Ram Allocated**
->10GB

**Additional context**
->Server is being hosted on Apex Hosting and their tech says that there is an issue with the modpack not matching with the client mod list.

**Comment by ChosenArchitect** [comment]
Will be fixed in the next update

**Comment by Nite-Hare** [comment]
Thanks!
