### ISSUE TITLE
Pylons Mod Suggestion

### ISSUE THREAD

**Issue by DEWSTREAMING** [ChosenArchitect/Project-Architect#122]
**Is your feature request related to a problem? Please describe.**
->Playing on a community server it can be annoying when unwanted visitors enter into my claim. Whether it's just their presence getting in the way which is annoying, or more troublesome issues such as people dropping items onto conveyor belts, or into item collectors, and clogging up or ruining your experience, and even just entering your claim to steal bees which aren't protected by ftb chunks, and I assume many other similar issues. Even when offline.

**Describe the solution you'd like**
->I would like the Pylons Mod to be added to the pack.

**Describe alternatives you've considered**
->The Pylons Mod allows you to place down Expulsion Pylons that keep out players from chunks. If someone enters into the chunk, they are sent back to their spawn point. You are able to whitelist players using items within the mod, and OP players are free to enter anytime as they should be. It's not the same as claiming, as from outside of the Pylon Chunk players could interact with an unclaimed chunk via range, but it provides what claiming does not, by keeping out strangers.

**Mod Sugestions**
->https://www.curseforge.com/minecraft/mc-mods/pylons

**Additional context**
->This Pylons mod is in the All The Mods 6 Modpack and upon learning about it, it has made my experience playing with my community a lot less stressful, as the issues listed at the top of this suggestion are no longer on my mind. 

If any other information is needed I will happily provide. Thank you.

**Comment by ChosenArchitect** [comment]
We have FTB Chunks that protect everything so add this mod.

**Comment by jpwanabe** [comment]
Not to disagree but FTB Chunks can be easily bypassed by a lot of the mods already in the pack. By non op uses.

**Comment by DEWSTREAMING** [comment]
Ah I'm sorry if I failed to make it clear on that part. This mod suggestion was in combination with FTB chunks. 

FTB chunks we've got and use, but it lacks in protecting certain aspects like stealing bees and other pets inside of claims with things like mob imprisonment tools, as well as failing to stop players from dropping items onto conveyor belts and clogging up the system causing machines to reject the new item on the belt and then other belts back up and suddenly thousands of items on the ground. As far as I'm aware FTB chunks doesn't prevent players from walking within a claim that isn't theirs, and so it doesn't protect against those attacks. If it does I have completely missed this and apologise in advance for missing that.

Pylons prevents unwanted players from entering the chunk entirely and thus stops them from getting close enough to do those things. It doesn't however stop players from standing outside of the claim and breaking/placing blocks as far as I know, so it would need to be in combination with FTB Chunks to get the best of both worlds. 

The blocks and whitelisting features are craftable ingame and non intrusive to players who have no need for them in single player or private servers, but on public community servers it would really be a life saver.

I realise I should have had all this in the original suggestion so I do apologise.

**Comment by ricepoly262** [comment]
Pylons would be a great addition to cover the bases that FTB Chunks does not

There are several ways that FTB Chunks can be currently bypassed or outright ignored, such as Explosive/Mining arrows from Apotheosis
FTB Chunks also does not block any entity interaction

Pylons allow players to simply stop unwanted visitors from even entering the chunks, period. You can add up to 9 players for a whitelist, and there's no problems for server managers as players with OP are ignored
They all use vanilla crafting so EMC values don't have to be added and they aren't a pain to make. 

There aren't really any other alternatives, Pylons simply teleports the players to their home location (bed, or spawn if they don't have one). It is nonfatal and causes no problems at all, the only other alternatives I can think of would be death, but even then that is difficult when you throw RM/Gem armor or Draconic Evolution into the mix.
