### ISSUE TITLE
Crushed Gold Appears as Forge:Dust/Lead instead of Forge:Dust/Gold

### ISSUE THREAD

**Issue by Revlejon** [ChosenArchitect/Project-Architect#125]
**Describe the bug**
->crushed gold (used to make electrum) is in the forge dictionary as lead dust instead of gold dust

**To Reproduce**
1. place squeezer
2. insert lead ore
3. smash lead ore
4. obtain crushed gold

**Expected behavior**
->i expect the lead ore to result in crushed lead (or lead dust) and gold ore to result in crushed gold

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![CrushedGold](https://user-images.githubusercontent.com/100461100/155832693-b459686e-0abe-4a54-acac-4b93dbbb4b33.png)

**Modpack version**
->1.7
**Java Version**
->jre8/jdk17
**Modpack Launcher Used**
->CurseForge
**Ram Allocated**
->8gb

**Additional context**
->

**Comment by jpwanabe** [comment]
As a side note, this breaks most of Thermal's upgrades due to the emc not being on create crushed ores.

**Comment by ChosenArchitect** [comment]
Fixed in next update. This was an oversite on my part... woops
