### ISSUE TITLE
Crashes when using nether portal and breaks save file

### ISSUE THREAD

**Issue by JeanVictorL** [ChosenArchitect/Project-Architect#126]
**Describe the bug**
when entering my nether portal, the game crashed during the loading, which i assume is also a save point, then the world doesn't open again on that file, i had to restore a backup. it might have been caused by entering the portal during a morph transformation.
->

**To Reproduce**
1. (just a guess) aproach portal while morphing is in progress
2. enter nether portal

**Expected behavior**
Complete crash and then failure to open that world again.
->

**Modpack version**
->1.7
**Java Version**
->1.8.0_321
**Modpack Launcher Used**
->CurseForge
**Ram Allocated**
->6gb

**Comment by James103** [comment]
Do you have the crash report? If so, can you please post it here?

**Comment by JeanVictorL** [comment]
sending you all my crash reports, i don't remember which one is the one, i believe its the most recent, so just in case i'm sending all of them.

if there's anything else i can do to help just let me know

[crash-reports.zip](https://github.com/ChosenArchitect/Project-Architect/files/8147461/crash-reports.zip)

**Comment by ChosenArchitect** [comment]
Be sure to load a backup from your backups folder to fix your world. This is something that might get fixed in a morph update if one ever comes out.

**Comment by JeanVictorL** [comment]
i create a new world twice before i learned that i could do that, but everything is fine now, at least i learned i can create backups manually too.

**Comment by roonian** [comment]
Just to add to this in case it helps:

I had a similar issue, though my save wasn't ruined. For me however, I was already morphed. Entered the portal, and  the game crashed. After reloading, I spawned in the nether somewhere around 500 blocks from my original location. I haven't tested it, but I think it tries to create a new portal spawn if your morphed
