### ISSUE TITLE
Powah: Missing EMC values

### ISSUE THREAD

**Issue by James103** [ChosenArchitect/Project-Architect#127]
**Is your feature request related to a problem? Please describe.**
Currently, many items from the Powah mod are missing EMC values, including all tiered items beyond Basic. This is because the underlying materials are missing EMC values as the recipes are of a type (Energizing) that ProjectE does not take into account by default.

**Describe the solution you'd like**
The following items are crafted using the Energizer from Powah and thus should have the following EMC values even though they don't:
* 2x Hardened Steel = 1x Iron Ingot + 1x Gold Ingot
  Therefore, 1x Hardened Steel = (256 + 2048) / 2 = 1152 EMC
* 1x Blazing Crystal = 4x Blaze Powder
  Therefore, 1x Blazing Crystal = 4 * 128 = 512 EMC
  (1x Blazing Crystal can also be made from 1x Blaze Rod (1536 EMC), but we're taking the least expensive option here)
* 1x Niotic Crystal = 1x Diamond
  Therefore, 1x Niotic Crystal = 8192 EMC
* 1x Spirited Crystal = 1x Emerald
  Therefore, 1x Spirited Crystal = 16384 EMC
* 16x Nitro Crystal = 1x Nether Star + 2x Redstone Block + 1x Block of Blazing Crystal
  = 1x Nether Star + 2x Redstone Block + 9x Blazing Crystal
  Therefore, 1x Nitro Crystal = (139264 + 2 * 576 + 9 * 512) / 16 = 9064 EMC
* 1x Ender Core = 1x Eye of Ender + 1x Dielectric Casing + 1x Basic Capacitor (Tiny)
  Therefore, 1x Ender Core = 1120 + 1192 + 202 = 2514 EMC
* 2x Blue Ice = 1x Dry Ice
  Therefore, 1x Dry Ice = 2 * 81 = 162 EMC
* 1x Charged Snowball = 1x Snowball
  Therefore, 1x Charged Snowball = 1 EMC

EDIT: Also forgot the following items in the initial pass:
* Player Transmitter requires Player Aerial Pearl which is obtained by using "an Aerial Pearl on Zombie or Husk."
  Therefore, 1x Player Aerial Pearl = 1x Aerial Pearl = 1440 EMC
* Binding card (Dimensional) is obtained by using "a Binding card on Enderman or Endermite."
  Therefore, 1x Binding card (Dimensional) = 1x Binding card = 244 EMC
* Lens of Ender is obtained by using "a Photoelectric Pane on Enderman or Endermite."
  Therefore, 1x Lens of Ender = 1x Photoelectric Pane = 3488 EMC

The above recipes were taken from JEI.

<details>
<summary> ProjectE commands to implement the above </summary>

```mcfunction
projecte setemc 1152 powah:steel_energized
projecte setemc 512 powah:crystal_blazing
projecte setemc 8192 powah:crystal_niotic
projecte setemc 16384 powah:crystal_spirited
projecte setemc 9064 powah:crystal_nitro
projecte setemc 2514 powah:ender_core
projecte setemc 162 powah:dry_ice
projecte setemc 1 powah:charged_snowball
projecte setemc 1440 powah:player_aerial_pearl
projecte setemc 244 powah:binding_card_dim
projecte setemc 3488 powah:lens_of_ender
```

</details>

**Describe alternatives you've considered**
One could make each Powah tier more expensive EMC-wise than the last, but that would require changing the recipes and would unbalance the game for non-ProjectE players.

**Comment by jpwanabe** [comment]
I have added these to my server and suggest that they be added to the pack as a whole as well. And draconic emc. I am currently adding that and will edit with values when I have them.

**Comment by ChosenArchitect** [comment]
No EMC will be added as its all automatable within this pack. If it had EMC then there would be no need for Power in the first place.
