### ISSUE TITLE
Respawning from the end

### ISSUE THREAD

**Issue by Nosster312** [ChosenArchitect/Project-Architect#128]
was collecting dragons breathe and fighting the ender dragon but upon killing a ender men I barely survived then was killed by the ender dragon where the bug started I got stuck in a state where my character was unable to move no matter what I tried (morph's, gamemode change, enderpearls) and thought a reboot of the world would fix it but the world loads to 100% but never boots and has no sign of a crash either.

1. N/A
**Expected behavior**
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->1.7
**Java Version**
->
**Modpack Launcher Used**
->Cursed Forge
**Ram Allocated**
->12G

**Additional context**
->

**Comment by ChosenArchitect** [comment]
I recommend using a backup from your backups folder and trying that. it should fix your issue. This is just an unfortunate sequence of events.
