### ISSUE TITLE
Morphing in to cave centipede and back will result in to extra appendages

### ISSUE THREAD

**Issue by Sw0rdSaint** [ChosenArchitect/Project-Architect#132]
**Describe the bug**
-> Morphing in to centipede then back to player model will result in to player with cave centipede tails, tails itself suffocate easily to blocks which can cause damage to player.

**To Reproduce**
1. kill cave centipede
2. Morph in to cave centipede
3. morph back to player model
4. Press F5

**Expected behavior**
-> morphing back to player model will result with centipede body still attached to the player. easily soffocates to blocks and cause damage to player

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

![2022-02-28_06 21 07](https://user-images.githubusercontent.com/99608484/155902562-32e6a474-6a97-4afd-842d-34e34804211b.png)

**Modpack version**
-> 1.7
**Java Version**
-> 8.0.51.16
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->8gb

**Additional context**
-> I killed myself to resolve issue by drowning

**Comment by ChosenArchitect** [comment]
I have removed this mob from the list but if you already have it you will need to remove it by hitting the delete key while having it selected.
