### ISSUE TITLE
Portable crafting does not work using jungle crafting table from crumbs

### ISSUE THREAD

**Issue by Sw0rdSaint** [ChosenArchitect/Project-Architect#133]
**Describe the bug**
->portable crafting from charm does not work

**To Reproduce**
1. get 4pcs jungle planks and craft into a jungle crafting table (crumbs) and place it in your inventory
2. click portable crafting table icon to test

**Expected behavior**
-> portable crafting icon does not work on jungle crafting table from crumbs

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

![2022-02-28_06 56 03](https://user-images.githubusercontent.com/99608484/155903485-74b02aca-8818-430e-9e74-bf668992b349.png)

**Modpack version**
-> 1.7
**Java Version**
->  8.0.51.16
**Modpack Launcher Used**
-> Curseforge
**Ram Allocated**
-> 8gb

**Additional context**
-> portable crafting icon does not work on jungle crafting table from crumbs

**Comment by ChosenArchitect** [comment]
https://github.com/ChosenArchitect/Project-Architect/issues/13
