### ISSUE TITLE
Dropping item to a lava bucket inside inventory to destroy does not work

### ISSUE THREAD

**Issue by Sw0rdSaint** [ChosenArchitect/Project-Architect#134]
**Describe the bug**
-> Dropping item to a lava bucket inside inventory to destroy does not work, tested inside sophisticated backpack and inventory

**To Reproduce**
1. get lava bucket
2. drag and drop an item to lava bucket to destroy (right clicking)
3. feature does not work

**Expected behavior**
-> expected to destroy any item that was dropped on the bucket of lava

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2022-02-28_06 59 49](https://user-images.githubusercontent.com/99608484/155903723-8868fa2d-6c2f-4fcf-9d7d-cd08936a49ee.png)
![2022-02-28_07 00 14](https://user-images.githubusercontent.com/99608484/155903730-9e4b49b3-3a2c-4e66-9a17-e153ce271fb5.png)

Modpack version
-> 1.7
Java Version
-> 8.0.51.16
Modpack Launcher Used
->Curseforge
Ram Allocated
->8gb

**Additional context**
->

**Comment by ChosenArchitect** [comment]
It's disabled so you don't make an oops and destroy your items. Unfortunately, it doesn't make the text go away.
