### ISSUE TITLE
item transfer node is destroyed when mined

### ISSUE THREAD

**Issue by Sw0rdSaint** [ChosenArchitect/Project-Architect#136]
**Describe the bug**
-> item transfer node is destroyed when mined

**To Reproduce**
1.  craft item transfer node from cyclic
2.  place block 
3.  mine item transfer node using pickaxe

**Expected behavior**
-> should drop item transfer node when mined

**Screenshots**
![2022-02-28_11 10 30](https://user-images.githubusercontent.com/99608484/155917982-9af76539-d9a1-43c8-971e-e3be2be7ba2d.png)
![2022-02-28_11 10 42](https://user-images.githubusercontent.com/99608484/155917992-e222b7ea-95d2-489c-90a3-1fbdaa05b6f1.png)
![2022-02-28_11 12 17](https://user-images.githubusercontent.com/99608484/155917997-d24f0252-5f91-4fed-b78d-a1678740b0c3.png)
![2022-02-28_11 12 24](https://user-images.githubusercontent.com/99608484/155918002-6de12786-3c53-4565-b291-a8f57a94f263.png)

If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

Modpack version
-> 1.7
Java Version
-> 8.0.51.16
Modpack Launcher Used
->Curseforge
Ram Allocated
->8gb

**Additional context**
->

**Comment by ChosenArchitect** [comment]
I will see if this mod has an update as this is related to the mod Cyclic.
