### ISSUE TITLE
It is possible to obtain Farmland using Exchangers, but it does not have an EMC value.

### ISSUE THREAD

**Issue by James103** [ChosenArchitect/Project-Architect#137]
**Describe the bug**
-> Using a higher-tier exchanger that can silk-touch, Farmland can be obtained by exchanging it with something else.

**To Reproduce**
1. Obtain at least a Diamond Exchanger.
2. Use it to exchange Farmland for something else.
3. Notice that the Farmland is obtained.

**Expected behavior**
-> Either Farmland should have an EMC value of 1 (`projecte setemc 1 minecraft:farmland`) or it should not be able to be obtained using Exchangers.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 1.7
**Java Version**
-> `C:/Program Files/Eclipse Adoptium/jdk-11.0.13.8-hotspot/bin/javaw.exe`
**Modpack Launcher Used**
-> MultiMC
**Ram Allocated**
-> `-Xms6144m, -Xmx6144m`

**Comment by ChosenArchitect** [comment]
Will add emc to that block.
