### ISSUE TITLE
More slabs with emc 

### ISSUE THREAD

**Issue by Winkiloves23** [ChosenArchitect/Project-Architect#139]
**Is your feature request related to a problem? Please describe.**
->A lot of slab don't have emc even though the blocks that you use to make them do 

**Describe the solution you'd like**
->give them emc 

**Describe alternatives you've considered**
->

**Mod Sugestions**
->None

**Additional context**
->

**Comment by James103** [comment]
If a slab is made from a block and the block EMC value is 1 or less, the slab can not have EMC as the resulting EMC value would also be less than 1.

**Comment by Winkiloves23** [comment]
> If a slab is made from a block and the block EMC value is 1 or less, the slab can not have EMC as the resulting EMC value would also be less than 1.
I see i didn't even think about that yeah that makes a lot of since thanks
