### ISSUE TITLE
Ram problems with loading into game and creating a world

### ISSUE THREAD

**Issue by Emerzone06** [ChosenArchitect/Project-Architect#14]
**Describe the bug**
->Whenever the screen moves changes to a new one it will say Not Responding in the top left of the window and then fix itself shortly after. The real problem is when trying to make a world if I click on the screen at all while it says Preparing World Creation it will instantly say (Not Responding). I do have windows 11 don't know if it would make a difference just thought I would mention it

**To Reproduce**
1. Open Project Architect on Windows 11
2. Wait for loading
3. create singleplayer world
4. click on screen while it says "Preparing World Creation"
5. Most clicks throughout getting to the New World menu will also start the Not Responding thing

**Expected behavior**
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

![image_2022-02-02_212554](https://user-images.githubusercontent.com/98931044/152276538-6d2c1950-26ec-44a1-ba21-a5adfbad5366.png)

**Modpack version**
->1.1
**Java Version**
->
**Modpack Launcher Used**
->Curse Forge
**Ram Allocated**
->I'm new to computers and mods so I don't really know what this means, sorry

**Additional context**
-> Don't have an amazing computer but can run games like RDR2 so I didn't think it would be a problem

**Comment by ChosenArchitect** [comment]
So the issue I see here is that you only gave the pack 3 gigs of ram. You need to go into your modpack launcher setting and bump up the ram to a least 6 if you have it available.

**Comment by Emerzone06** [comment]
That worked perfectly, I thank you greatly
