### ISSUE TITLE
Certain job blocks do not convert villagers

### ISSUE THREAD

**Issue by NotPiffany** [ChosenArchitect/Project-Architect#140]
**Describe the bug**
Barrels, beehives, and woodcutters are not acting as job blocks, but JEI says they should.

**To Reproduce**
1. Place a barrel/beehive/woodcutter in the world
2. Put a jobless villager near the barrel/beehive/woodcutter
3. Wait.

**Expected behavior**
JEI says that a barrel should create a fisherman, a beehive should create a beekeeper, and a woodcutter should create a lumberjack.

**Modpack version**
-> 1.7

**Java Version**
-> Version 8 update 231

**Modpack Launcher Used**
-> GDLauncher

**Ram Allocated**
-> 10086 MB

**Additional context**
-> The other job blocks all work as expected.

**Comment by James103** [comment]
1. Villagers only work between 8:00 am and 3:00 pm each in-game day. Otherwise, they will try to gather (look for a bell), sleep (look for a bed), or just wander.
2. Make sure that there are no other workstations that the villager can reach within ~32 blocks. If the villager can reach other workstations, it will (likely) prefer to work elsewhere.
3. Make sure that the villager is not a nitwit.
4. If all else fails, you may need to run `/data get entity @e[type=villager,limit=1,sort=nearest]` while standing near the villager and post the output (from the logs) here.

**Comment by NotPiffany** [comment]
1. I waited for more than an in-game day each time.
2. I had them isolated in a room with only a bed and a job block each time.
3. Each villager converted to another occupation as soon I changed the job block in their room.
4. I'll have to try this later.

**Comment by Winkiloves23** [comment]
> 1. I waited for more than an in-game day each time.
> 2. I had them isolated in a room with only a bed and a job block each time.
> 3. Each villager converted to another occupation as soon I changed the job block in their room.
> 4. I'll have to try this later.

If you have some job blocks around them even if they are isolated they will some times try to path find towards it so make sure to pick up all job blocks that haven't been taken from a another villager up was idk if this will help but this can happen

**Comment by NotPiffany** [comment]
Ok, I tried it with a villager near a barrel. It's during the day, and he's over 40 blocks away from any other villagers. This is what I got from the command James103 posted. Does this help?

Villager has the following entity data: {Brain: {memories: {"minecraft:home": {value: {pos: [I; 1234, 71, -395], dimension: "minecraft:overworld"}}, "minecraft:last_slept": {value: 5608613L}, "minecraft:last_woken": {value: 5612537L}}}, HurtByTimestamp: 0, ForgeData: {}, Attributes: [{Base: 0.5d, Name: "minecraft:generic.movement_speed"}, {Base: 0.08d, Name: "forge:entity_gravity"}, {Base: 0.0d, Name: "minecraft:generic.knockback_resistance"}, {Base: 48.0d, Modifiers: [{Amount: 0.07115333485962737d, Operation: 1, UUID: [I; -1313351505, 1272859409, -1942891125, 757208435], Name: "Random spawn bonus"}], Name: "minecraft:generic.follow_range"}], FoodLevel: 0b, Invulnerable: 0b, FallFlying: 0b, ForcedAge: 0, Gossips: [], PortalCooldown: 0, AbsorptionAmount: 0.0f, LastRestock: 0L, FallDistance: 0.0f, CanUpdate: 1b, DeathTime: 0s, Xp: 0, LastGossipDecay: 5612373L, ForgeCaps: {"tombstone:cap_protected_entity": {active: 0b}, "citadel:extended_entity_data_citadel": {}}, HandDropChances: [0.085f, 0.085f], PersistenceRequired: 0b, UUID: [I; 1682694659, 1705263271, -1291818766, -693426488], Age: 0, Motion: [0.0d, -0.0784000015258789d, 0.0d], Health: 19.0f, KubeJSPersistentData: {}, LeftHanded: 0b, Air: 300s, OnGround: 1b, CitadelData: {}, Rotation: [175.73682f, 0.0f], HandItems: [{}, {}], RestocksToday: 0, ArmorDropChances: [0.085f, 0.085f, 0.085f, 0.085f], Pos: [1232.5369927403526d, 71.0d, -396.02228771959324d], Fire: -1s, ArmorItems: [{}, {}, {}, {}], CanPickUpLoot: 1b, VillagerData: {profession: "minecraft:none", level: 1, type: "minecraft:plains"}, HurtTime: 0s, Inventory: []}

**Comment by ChosenArchitect** [comment]
In my tests, all blocks work...
