### ISSUE TITLE
Add Bad wither no cookie

### ISSUE THREAD

**Issue by jpwanabe** [ChosenArchitect/Project-Architect#141]
**Is your feature request related to a problem? Please describe.**
->Adding BWNC will silence the wither and ender dragon death sounds across the server

**Describe the solution you'd like**
-> Who wants to hear someone farm the endder dragon???

**Describe alternatives you've considered**
->Crying in a corner every time I hear *that* sound

**Mod Sugestions**
->https://www.curseforge.com/minecraft/mc-mods/bad-wither-no-cookie-reloaded

**Additional context**
->

**Comment by derrickmehaffy** [comment]
Since this is fixed, can we close it?
