### ISSUE TITLE
Can't automate potion brewing (IndustralForgoing)

### ISSUE THREAD

**Issue by DeathLichWing** [ChosenArchitect/Project-Architect#143]
**Describe the bug**
-> Industrial Foregoings potion brewer stacks the outputted bottles but it needs to be spread out between the 3 pink boxes to allow the next desired potion effects to brew 

**To Reproduce**
Steps to reproduce the behaviour:
1. Place water, blaze, bottles in the spots shown
2. Add desired potions effects that your want to use I.E nether wart then glistering melon to make health potions 
3. 
4. 

**Expected behaviour**
-> Potion Brew should automatically brew the desired potion with the sequence of mats used for the desired potion

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2022-03-02_23 09 22](https://user-images.githubusercontent.com/17900661/156341495-4211745b-536f-4023-b1fd-9c60d52ff9d7.png)
![2022-03-02_23 09 28](https://user-images.githubusercontent.com/17900661/156341518-d78735e5-023c-4877-96fd-87895c597f7b.png)

**Modpack version**
->1.7
**Java Version**
->1.16.5
**Modpack Launcher Used**
->CurseForge with vanilla java launcher
**Ram Allocated**
->15gb

**Additional context**
->First screenshot shows the starting water bottles needed to start brewing but the bottles are stacked. Second screenshot shows that I took 2 bottles off and it created 1 health potion.
Just need to stop whatever mod that is stacking items to not for this machine.

**Comment by ChosenArchitect** [comment]
so to automate you would need to have a brewer for each one you want to automate and then put the supplies in the slots and lock the recipe.
