### ISSUE TITLE
System crashed when breaking tank

### ISSUE THREAD

**Issue by Navop** [ChosenArchitect/Project-Architect#145]
When a tank is full of liquid meat, breaking it with a pick axe minecraft error occurs.

	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3909053984 bytes (3727 MB) / 8422162432 bytes (8032 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8

To reproduce

Mob farm with mob slaughter , liquid slime on left side, liquid meat right side, in separate tanks that is entangled to refine storage

Once tank is full break liquid meat tank ... crash occurs ...

[latest.log](https://github.com/ChosenArchitect/Project-Architect/files/8182158/latest.log)

**Comment by ChosenArchitect** [comment]
When I test I am not able to repeat this issue. I would also need a Crash log not the latest.log
