### ISSUE TITLE
Mods Fails When Loading the Game

### ISSUE THREAD

**Issue by itsRyoui** [ChosenArchitect/Project-Architect#15]
**Describe the bug**
-> Mods failed on load. The error doesn't show what mods fail.

**To Reproduce**
1. Open Pack
2. Wait for the Mods to Load
3. Mods Failed

**Expected behavior**
-> To load into the Minecraft Menu

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image](https://user-images.githubusercontent.com/53822699/152276239-116cd5b3-ad94-45c8-a797-f80b93886fd4.png)

**Modpack version**
-> 1.0.0
**Java Version**
-> JDK 17.0.1
**Modpack Launcher Used**
-> MultiMC
**Ram Allocated**
-> 8 GB

**Additional context**
->

**Comment by ChosenArchitect** [comment]
This could be an issue with whatever launcher you are using... Make sure the launcher downloads everything before trying to launch it. I recommend trying again and getting back with me here.

**Comment by PlayerAndCoder** [comment]
I have the exact same problem, i also use MultiMC. My logs and i use Java 16.0.2
[2022-02-03-2.log.gz](https://github.com/ChosenArchitect/Project-Architect/files/7997551/2022-02-03-2.log.gz)
.

**Comment by ChosenArchitect** [comment]
I believe this is a issue with multimc selecting the wrong forge version. I recommend trying another launcher like the GD launcher or curseforge.

**Comment by Joomzy** [comment]
Using Java 17 on minecraft versions at 1.16.5 or below will cause issues with some mods, a fix for this is to make sure you have a version of java 8 installed and letting multimc use the java 8 for modpacks that use 1.16.5 and under and 1.17 on packs above 1.16.5. Currently java 8_311 works perfect for Project Architect, 321 has some issues though.

**Comment by aSigma313** [comment]
could u send me a link of java 8 download pls
