### ISSUE TITLE
All slimes are showing the small slime texture, but are actually big/medium/small slimes.

### ISSUE THREAD

**Issue by roonian** [ChosenArchitect/Project-Architect#150]
**Describe the bug**
-> Big and medium slimes show small slime texture and possibly hitbox, however they are damaging you as if they are big/medium slimes (damaging you from 2-3 blocks away)

**To Reproduce**
1.  Find slime

**Modpack version**
->1.8
**Modpack Launcher Used**
-> CurseForge

**Comment by ChosenArchitect** [comment]
Seems like a nonissue as hitboxes seem fine!
