### ISSUE TITLE
Easy Villager Mods

### ISSUE THREAD

**Issue by Winkiloves23** [ChosenArchitect/Project-Architect#151]
**Is your feature request related to a problem? Please describe.**
->not a problem just suggesting this so its a lot easier to reset villagers trades so you can get the enchantments that you want 

**Describe the solution you'd like**
->add the mod 

**Describe alternatives you've considered**
->

**Mod Sugestions**
->Easy Villager mods

**Additional context**
->

**Comment by James103** [comment]
Duplicate of #35
