### ISSUE TITLE
Item duplication glitch 

### ISSUE THREAD

**Issue by Winkiloves23** [ChosenArchitect/Project-Architect#157]
**Describe the bug**
->When you enchant a item with the Cincinnasite Anvil your item that you are trying to enchant will duplicate and the enchanted book will not be consumed 

**To Reproduce**
1. place down the Cincinnasite Anvil 
2. Get a item you want to enchant 
3. enchant that item 
4. item will be duplicated 

**Expected behavior**
->To enchant my weapon and have the enchanted book be consumed but not have it be duplicated 

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
https://gyazo.com/2d6d611acfb66314b4d05d1e7006b249 
**Modpack version**
->1.8
**Java Version**
->1.8.0_321
**Modpack Launcher Used**
->CursedForge
**Ram Allocated**
->7G

**Additional context**
->if you try to enchant a draconic item that has modules in them those will also duplicate as well

**Comment by Thunder-Nova** [comment]
![2022-03-14_15 21 45](https://user-images.githubusercontent.com/31967337/158266413-c06e1072-b3e3-458b-9584-9f9c5e797fc1.png)
yep confirming it
