### ISSUE TITLE
Duplication of liquids with Tinker's Tanks and Auto Item Refiller Bracelet

### ISSUE THREAD

**Issue by Neko3241** [ChosenArchitect/Project-Architect#16]
**Describe the bug**
-> Duplication of liquids with Tinker's Tanks and Auto Item Refiller Bracelet

**To Reproduce**
1. fill a seared fuel tank with any liquid from a tinker's smeltery
2. have 1 tank (filled with liquid) inside your hotbar.
3. Place tank down while having enough emc for Auto Item Refiller Bracelet to refill the item
4. see 16x tanks filled with liquid appear in your hotbar

**Expected behavior**
-> I expected that placing down a tank filled with liquid would give a empty tank back to fill the slot, and not one filled with the same liquid as what was last placed.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> Modpack Version 1.0
**Java Version**
-> 
**Modpack Launcher Used**
-> Curseforge 
**Ram Allocated**
-> 10048 mb

**Additional context**
->

**Comment by ChosenArchitect** [comment]
Mod was removed (Multiple Issues with it)
