### ISSUE TITLE
Failed to load 2 mods

### ISSUE THREAD

**Issue by Martine1231** [ChosenArchitect/Project-Architect#168]
Using MultiMc 5 version 0.6.15-3247 on win32
1. Download Project Architect from CurseForge tab
2. Run Project Architec
[ProjectArchitect Mod Loading Erroe latest.log](https://github.com/ChosenArchitect/Project-Architect/files/8403456/ProjectArchitect.Mod.Loading.Erroe.latest.log)
[ProjectArchitect Mod Loading Error Crash Report.txt](https://github.com/ChosenArchitect/Project-Architect/files/8403457/ProjectArchitect.Mod.Loading.Error.Crash.Report.txt)
![ProjectArchitect Mod Loading Error](https://user-images.githubusercontent.com/67770237/161403205-26a2eccd-d563-4a8d-817b-f051c3238405.PNG)
t

**Comment by James103** [comment]
From the crash report:
> Java Version: 17.0.1, Oracle Corporation
>	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation

Will you please try downgrading your Java to version 11? If that doesn't work, try running with Java 8 or Java 14.
There are some changes in recent Java releases that cause crashes as described above.

NOTE: If you still want to play versions 1.17 and up, you will need to keep your Java 17 installation and install Java 11 as a separate installation.
