### ISSUE TITLE
ProjectE Progression Locked?

### ISSUE THREAD

**Issue by Immortalia** [ChosenArchitect/Project-Architect#17]
ProjectE doesnt let you progress to Dark Matter due to some issue with the crafting recipes of EMC Baubles being disabled, i think?
Not entirely sure what's wrong but you need Clay Matter in order to make Dark Matter and you dont seem to be able to make Clay Matter. Not sure if i'm doing something wrong or not.

**Modpack version**
->1.1

**Modpack Launcher Used**
->CurseForge
**Ram Allocated**
->12GB

**Comment by ChosenArchitect** [comment]
Removed EMCBaubles as it was causing LOTS of Issues.
