### ISSUE TITLE
Crashes When I Open or creat a new world

### ISSUE THREAD

**Issue by Reaxplayz** [ChosenArchitect/Project-Architect#18]
**Describe the bug**
->the Game crash when i open or creat a new wolrd

**To Reproduce**
1. I go to Singleplayer
2. Creat a new wolrd
3. It starts
4. When it reaches 100% it says saving wolrd and it crash

**Expected behavior**
->The Game should load and get me into a world

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->1.0
**Java Version**
->1.16.5
**Modpack Launcher Used**
->TLauncher
**Ram Allocated**
->10Gbs

**Additional context**
->Pls try to fix it and pls don't ignore me because I'm using TLauncher

**Comment by ChosenArchitect** [comment]
TLauncher is a cracked client and I don't support this launcher or condone it's use.
