### ISSUE TITLE
Nerf/Reduce the amount of EMC you get though Dimensional Shards

### ISSUE THREAD

**Issue by Dcraftbg** [ChosenArchitect/Project-Architect#2]
**Is your feature request related to a problem? Please describe.**
-> You gain a lot of Dimensional Shards when breaking them with or without fortune. You gain a lot of EMC using that which basically means you skip the entirety of early game. From just 2 stacks of them (about 20 ore blocks) you gain over 2 million EMC in that case you will probably be able to get any item in the entire game marking things like storage systems or complicated machines unnecessary or entirely pointless.

**Describe the solution you'd like**
->
 You can reduce the amount of Shards you get per ore. Alternatively you can also reduce or even remove the EMC value of the item. 
**Describe alternatives you've considered**
->You can also change the way that this ore spawns using kubejs to make it more rare to find.

**Mod Sugestions**
->You can use kubejs to change how things function . Its very simple and easy to use

**Additional context**
-> If you change the way that this functions it will make early game a lot more challenging and things like diamonds and expensive pieces of equipment a lot harder to get!

**Comment by ChosenArchitect** [comment]
I removed EMC from the shards as they arent used for much other than RFTools to upgrade them.
