### ISSUE TITLE
Crashes When I Try to Morph

### ISSUE THREAD

**Issue by Steelbot2803** [ChosenArchitect/Project-Architect#20]
**Describe the bug**
->The game crashes when I try to morph into any entities I have killed.

**To Reproduce**
1. Kill an entity
2. Morph into said entity 

**Expected behavior**
->I should be able to morph into that entity and continue playing.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->1.0
**Java Version**
->1.16.5
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->10 GB

**Additional context**
->Crash Report: 
[crash-2022-02-03_16.49.01-client.txt](https://github.com/ChosenArchitect/Project-Architect/files/7994101/crash-2022-02-03_16.49.01-client.txt)

**Comment by ChosenArchitect** [comment]
From the looks of things you are using Optfine... Try playing the pack without and see if the crash persists.

**Comment by Steelbot2803** [comment]
Thanks for the reply but I think I resolved it.....Seems to be an issue with a resource pack I was using. Once I deleted it I haven't faced any crashes.
