### ISSUE TITLE
Modpack will not start with latest Java version

### ISSUE THREAD

**Issue by Joomzy** [ChosenArchitect/Project-Architect#21]
**Describe the bug**
->Project Architect will not start in java 8_321

**To Reproduce**
1. Install Java 8_321
2.  Run Modpack
3. 
4. 

**Expected behavior**
-> Modpack to start

**Modpack version**
-> 1.0.0
**Java Version**
-> v8_321
**Modpack Launcher Used**
-> MultiMC
**Ram Allocated**
-> 6G

**Additional context**
-> Modpack works wonders on Java 8_311 but will not start in 8_321. I'm unsure whether this is something that can get fixed on your side but it would be nice to add it into the descriptions on the modpage.

**Comment by Waoweens** [comment]
I am also experiencing this issue with 8_322. Updating forge to latest seems to have fixed it.
To update forge with MultiMC go to edit instance > version > forge > change version > pick latest > OK

**Comment by fuelhauler** [comment]
I found that Forge 36.2.26 had the same problem as 36.2.20.

Version 36.2.25 worked, however.

**Comment by ChosenArchitect** [comment]
This is a issue with the latest Java version. I recommend reverting back. This is a forge issue and not the modpack s issue.
