### ISSUE TITLE
Low Fps rate

### ISSUE THREAD

**Issue by TheWolffie** [ChosenArchitect/Project-Architect#22]
Had now issue when first launched but now average frames in both windowed and full screen is at 2 to 8 fps
![Minecraft Fps drop](https://user-images.githubusercontent.com/98964590/152364824-64c4f240-f3dd-4b6b-b60f-59a89e961d2c.png)

**Comment by ChosenArchitect** [comment]
I don't really know how to go about fixing this as I haven't experienced it. I also have no way of testing it either...

**Comment by plinio-jrm** [comment]
Chosen, you could add Optifine to your modpack.
I'm trying to add the 1.16.5 version of optiFine and the client doesn't load it. Not everyone have a beef computer as you have.
I have 16GB, Vega 64 and Ryzen 5 2gen. I'm getting low FPS like crazy.

**Comment by joldfield101** [comment]
> Chosen, you could add Optifine to your modpack. I'm trying to add the 1.16.5 version of optiFine and the client doesn't load it. Not everyone have a beef computer as you have. I have 16GB, Vega 64 and Ryzen 5 2gen. I'm getting low FPS like crazy.

I installed Optifine on this - it ran, but still tops out at 40fps. (no its not the spec of the PC!)

**Comment by plinio-jrm** [comment]
> > Chosen, you could add Optifine to your modpack. I'm trying to add the 1.16.5 version of optiFine and the client doesn't load it. Not everyone have a beef computer as you have. I have 16GB, Vega 64 and Ryzen 5 2gen. I'm getting low FPS like crazy.
> 
> I installed Optifine on this - it ran, but still tops out at 40fps. (no its not the spec of the PC!)

Hey. i managed to install OptiFine G6 and in Chosen discord in #support i posted my settings screenshots. Helped alot of people to play the game. I'm getting good fps with even render distance of 32 chunks.

**Comment by joldfield101** [comment]
If you are using foamfix go to the config --> foamfix and then change

# Disables texture animations. [default: false] 
B:disableTextureAnimations=false

# Disables texture animations. [default: false]
B:disableTextureAnimations=true

if that did not work then press shift+F3 and see what causing all the lag then look for a solution on google or somthing
