### ISSUE TITLE
open bc of the datapacks of the mods are out of date, it gives an error while creating a world 

### ISSUE THREAD

**Issue by superstyle790** [ChosenArchitect/Project-Architect#23]
**Describe the bug**
->

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->
**Java Version**
->
**Modpack Launcher Used**
->
**Ram Allocated**
->

**Additional context**
->

**Comment by ChosenArchitect** [comment]
The data packs that are in the modpack are added by the mods. They might show out of date but that's not.

**Comment by ChosenArchitect** [comment]
I recommend redownloading the modpack and trying again as it could have had a download issue as curseforge can be finicky sometimes.
