### ISSUE TITLE
Silicon smelting recipe unavailable

### ISSUE THREAD

**Issue by Joomzy** [ChosenArchitect/Project-Architect#24]
**Describe the bug**
-> To obtain silicon for refined storage you have to smelt a single piece of quartz crystal in a furnace but this overlaps with the same recipe that smelts a single quartz crystal into quartz glass

**To Reproduce**
1. Grab a quartz crystal
2. Smelt it

**Expected behavior**
-> Smelting the quartz crystal should give you a single piece of silicon.

**Modpack version**
-> 1.0.0
**Java Version**
-> java 8u311
**Modpack Launcher Used**
-> MultiMC
**Ram Allocated**
->8G

**Additional context**
-> Easiest way for this to be solved is to either remove the crafting recipe for quartz glass so it doesn't overlap with the silicon OR change the quartz glass recipe to need to smelt a quartz block to obtain 4 quartz glass. This would keep the crafting cost the same.

**Comment by ChosenArchitect** [comment]
Will work on this today!
