### ISSUE TITLE
Create mod copper ore can be crafted from a block of copper

### ISSUE THREAD

**Issue by T-Bunney** [ChosenArchitect/Project-Architect#25]
**Describe the bug**
->Craft a block of copper and then try to craft ingots from the block of copper and copper ore will be crafted instead.

**To Reproduce**
1. Craft 9 copper into a block of copper.
2. Put a block of copper into a crafting table.

**Expected behavior**
->9 copper ingots are supposed to be crafted from a block of copper.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![Captu54re](https://user-images.githubusercontent.com/56650855/152411745-5792960e-ad92-4c32-9dfa-d3d5c924a305.PNG)

**Modpack version**
->1.1
**Java Version**
->Java 8
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->9GB

**Additional context**
->

**Comment by ChosenArchitect** [comment]
Issue was fixed last night and will be fixed in the next update!
