### ISSUE TITLE
Fails to load 2 mods

### ISSUE THREAD

**Issue by KittyFloof** [ChosenArchitect/Project-Architect#26]
**Describe the bug**
-> mc is crashing due to unloaded mods

**To Reproduce**
1. no idea, ill provide details of my setup

2. I'm using MultiMC and found the pack both through its own curse forge lookup, and by downloading the pack from the website. I've tried restarting, reinstalling, swapping forge versions, even java versions but nothing is running. with java 8 the pack wont run at all with java 16 the pack loads all but 2 mods and doesn't say what they are. I've tried another modpack that works with java 8 and it runs fine, then I tried one of the same version as your pack and it works fine on java 16. it doesn't list the mods that can't be loaded.

3. Looking into the logs I can see that "cb_microblock" failed to load
![Screenshot 2022-02-03 162622](https://user-images.githubusercontent.com/98986305/152431612-b7c4506a-e830-45b5-a336-fa7e79de0702.png)

4. I also see "projectred-illumination" failed to load
![Screenshot 2022-02-03 163049](https://user-images.githubusercontent.com/98986305/152432251-380fbb33-9722-4325-84fa-457fc07971ac.png)

**Expected behavior**
-> run the pack with mods loading.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

![Screenshot 2022-02-03 160246](https://user-images.githubusercontent.com/98986305/152429517-9a5774c1-2d53-4a39-820a-6844422f95e9.png)

**Modpack version**
-> 1.0
**Java Version**
->16.0.2
**Modpack Launcher Used**
->MultiMC

**Ram Allocated**
->8gb (8192 MiB both min/max)

**Additional context**
-> none that I can think of or that hasn't already been provided

**Comment by KittyFloof** [comment]
just to update, it seems to work using the curseforge application, multiMC doesnt seem to like this pack for some weird reason. this isnt ideal since I prefer the ease of using multimc rather than a special loader for a specific modpack.

**Comment by YasinandHajar** [comment]
I had the same problem with microblocks on multimc but here is my fix:
1) Click on the modpack in multimc and then click "edit instance"
2) go to settings and check the box that says "java installation"
3) click on auto detect and you need to select the correct version of java. Forge supports java 8.

for step 3 you might have multiple versions of java 8; Just select one and launch, if it doesnt work move on to the next version.
