### ISSUE TITLE
mod Suggestions

### ISSUE THREAD

**Issue by litPanda2129** [ChosenArchitect/Project-Architect#27]
**Is your feature request related to a problem? Please describe.**
->Can you add a vein miner mod and FTB Essentials or a mod like it?

**Describe the solution you'd like**
->

**Describe alternatives you've considered**
->

**Mod Sugestions**
-> FTB Essentials and FTB Ultimine 

**Additional context**
->
FTB Essentials so players can set homes and FTB Ultimine because I am lazy and don't feel like doing everything manually. 🙂

**Comment by ChosenArchitect** [comment]
You can always add those mods yourself.

**Comment by litPanda2129** [comment]
thank you I will try that.
