### ISSUE TITLE
EMC duping

### ISSUE THREAD

**Issue by Dcraftbg** [ChosenArchitect/Project-Architect#3]
Not really a big issue but you can dupe EMC using creates saw and logs as you can get 6 planks out of 1 log .1 log has a value of 32 and planks have a value of 8 which is basically 48 EMC for 32 EMC.

**Comment by ScorpioneOrzion** [comment]
This should not really be a problem, due to their are more powerful ways to generate EMC.
One way would be to just have a bamboo farm or so.

**Comment by Spykiller45** [comment]
yea this isnt an issue..and...why try to suggest that we dont cheese the emc using create....its single player people will do what they want..and if that is a create powered plank based emc farm...who cares..only you the fun police

**Comment by Dcraftbg** [comment]
> yea this isnt an issue..and...why try to suggest that we dont cheese the emc using create....its single player people will do what they want..and if that is a create powered plank based emc farm...who cares..only you the fun police

yea its not really a bug just saying because ores have no EMC values :|

**Comment by ChosenArchitect** [comment]
Yea, So when you have EMC in the modpack there is totally going to be issues like this that are really not that fixable. If I removed the EMC from wood it would affect everything in the modpack that uses wood.
