### ISSUE TITLE
Project EX

### ISSUE THREAD

**Issue by Flozz2** [ChosenArchitect/Project-Architect#30]
Project EX is a great addition to project E, it has EMC link in wich you can put items that are transformed into emc, bonsai flowers that are easier to use and smaller, a better tablet with crafting, etc, I think you should consider it.
![Pex](https://user-images.githubusercontent.com/99019908/152519382-0465f5b2-949e-4369-8fc6-b4048f7abd4d.jpg)
![Pex (2)](https://user-images.githubusercontent.com/99019908/152519406-4eb60156-2241-4766-8a26-d92ed51b8ab1.jpg)
(those aren't my screenshots)

**Comment by Anders206** [comment]
Project EX would actually be nice in here, but it also feels a little op.

**Comment by Mini-kun** [comment]
> Project EX would actually be nice in here, but it also feels a little op.

About that. Chosen can make them cost more and even higher EMC to get them aswell.

**Comment by Flozz2** [comment]
> 

Maybe reduce the EMC output would be good.

**Comment by Mini-kun** [comment]
That works two

**Comment by ChosenArchitect** [comment]
This mod is no longer being updated for 1.16 and isn't finished. The personal EMC links don't work and the only thing that does work is the botany generators. This mod was in the pack but was removed as it is no longer being supported in this version.
