### ISSUE TITLE
Mod Suggestion

### ISSUE THREAD

**Issue by Civil69420** [ChosenArchitect/Project-Architect#32]
I have a mod suggestion called chisel and bits of you have not added it already. If you didn’t know what it is then it’s a mod where it allows you to build with smaller blocks which can allow you to make custom blocks. 
I’m not sure if you can use modded blocks but it just allows some more creativity and more design options. Here’s the curseforge link: https://www.curseforge.com/minecraft/mc-mods/chisels-bits

**Comment by ChosenArchitect** [comment]
I just feel like this mod will add to the mod list without being used much. I'm trying to keep the mod list low
