### ISSUE TITLE
immersive portals mod

### ISSUE THREAD

**Issue by Anders206** [ChosenArchitect/Project-Architect#34]
**Is your feature request related to a problem? Please describe.**
-> No, It's not related to a problem

**Describe the solution you'd like**
->I would love to see immersive portals get added to Project Architect since the mod makes portals so much prettier and the way you can use them in builds, and also the fact that I haven't seen the mod in many mod packs which I think is a shame. And it also adds the feature for you to place portals horizontally instead of only placing them vertically.

**Describe alternatives you've considered**
-> I Don't think there are other mods that do what immersive portals do

**Mod Suggestions**
-> immersive portals mod

**Additional context**
-> 
![image](https://user-images.githubusercontent.com/63259225/152580716-6c2bcd97-be08-443f-93da-47e137c37fab.png)

**Comment by lewapro** [comment]
Immersive portals mod is not supported for forge 1.15.2+ therefore it can't be added.
Description says 1.16 works only with optifine too, but optifine conflicts with morph.

**Comment by wackoman6789** [comment]
Works great without optifine.
As a side note its a really cool mod that I wish was in more packs.
Edit: it works completely fine with optifine G7 no idea why G8 doesn't work tho

**Comment by ChosenArchitect** [comment]
This is a client-side mod that you can always add yourself.
