### ISSUE TITLE
Suggestion of an Mod

### ISSUE THREAD

**Issue by xNicolas99** [ChosenArchitect/Project-Architect#35]
**Is your feature request related to a problem? Please describe.**
->Frustrated when trading with Villagers. You can make it easier by adding the mod linked below.

**Describe the solution you'd like**
->Adding the Easy Villager mod.

**Describe alternatives you've considered**
->Noone. Its a handy mod so i thought cant hurt to suggest adding it in future versions.

**Mod Sugestions**
->https://www.curseforge.com/minecraft/mc-mods/easy-villagers

**Additional context**
->Easy Villagers makes breeding, trading as well as growing villagers easier.

**Comment by ChosenArchitect** [comment]
This mod causes issues with other mods that require you to pick up villagers.
