### ISSUE TITLE
Silk touching spawners doesn't drop them

### ISSUE THREAD

**Issue by PaleBlu** [ChosenArchitect/Project-Architect#36]
When using any pickaxe with the enchant silk touch on it the spawner drops xp instead of the spawner itself.
->

**To Reproduce**
1. Have a pickaxe enchanted with silk touch
2. Break spawner with said pickaxe
3. Search inventory frantically for said spawner
4. Admit defeat and report the bug

**Expected behavior**
Spawner item to drop on break
->

**Modpack version**
->v1.1
**Java Version**
->36.2.26
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->10gb

**Comment by Mini-kun** [comment]
If i may ask have it ever been a thing in the Normal pack/ a mod that Chosen has talk about Because I dracnoie has it core that you can use on them to Get the mobs Then you can change the type with the mob soul.

**Comment by PaleBlu** [comment]
What I'm referring to is a unique mechanic added by the mod apotheosis. I am aware of the draconic evolution mechanic but I'm reporting the bug for a specific mod and issue with said mod.

**Comment by ChosenArchitect** [comment]
This feature is Disabled because Draconic is in the modpack. Apotheosis is in the modpack but the spawner feature is disabled.
