### ISSUE TITLE
Quest lines for each mod

### ISSUE THREAD

**Issue by Dcraftbg** [ChosenArchitect/Project-Architect#4]
Mods are confusing and many times than not players get confused on what to do.
I know that Chosen said that there shouldn't be any quest lines but im talking about individual quest lines for different mods.
For example a quest line for thermal, Refined storage, Bigger Reactors and others! They are not like usual progression where you have specific tasks but more like info for each part of the mod. Having some way of telling beginners what mod does what is a great way of letting them know what they want to do and what they choose to ignore!
By having INFO for mods will make the player base larger and for more than "I know what to do and when to do it" and more like "I can do this and that because that seems interesting and something that i can do"

**Comment by ChosenArchitect** [comment]
If you have an issue with no quest I recommend using the L key to follow the Quest that the mod devs provide in the advancements. I will not be adding quest.
