### ISSUE TITLE
My game dose not load mods

### ISSUE THREAD

**Issue by aSigma313** [ChosenArchitect/Project-Architect#42]
)Describe the bug
-> whenever I try to open it, there seems to be errors loading 3 mods. Those mods are Better Nether Reforged, Portality, and Titanium.

To Reproduce

open the game
let it load
errors pop up
Expected behavior
-> I expected to be able to open the game and play

Screenshots
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
image

Modpack version
-> 1.1
Java Version
-> 1.8.0_51
Modpack Launcher Used
-> CurseForge (the app)
Ram Allocated
-> 7-8GB

**Comment by Beard-Bois** [comment]
Close the Curseforge app, and relaunch it. Then redownload the modpack

**Comment by aSigma313** [comment]
i did that
