### ISSUE TITLE
Server edition

### ISSUE THREAD

**Issue by TGHamza** [ChosenArchitect/Project-Architect#44]
->can you make a server edition in curseforge cause i want to make a server with my friends

**Comment by Mini-kun** [comment]
one thing u can do for the time been is get The Config, Defaultconfigs, Kubejs, Mods, and download forge 36.2.26 from [files.minecraftforge.net](https://files.minecraftforge.net/net/minecraftforge/forge/index_1.16.5.html)

**Comment by TGHamza** [comment]
Can i ask you something

**Comment by Mini-kun** [comment]
yes go ahead :)

**Comment by TGHamza** [comment]
Can you send me a link for your modpack but not from curseforge from any
website ex mideafire pls

**Comment by Mini-kun** [comment]
Here is for the version 1.1 :)
[Download server Files v1.1
](https://1drv.ms/u/s!Aqsyx25sSM05lOhmuJ_9Jn2iRVCs2Q?e=laXICZ)

**Comment by TGHamza** [comment]
Thank you very much

**Comment by Mini-kun** [comment]
yw :)

**Comment by ChosenArchitect** [comment]
Server Files will be out after it's out of BETA I will not support server files if there are issues till then.

**Comment by TGHamza** [comment]
Got it, thanks!
