### ISSUE TITLE
Morph + Trinket's compability

### ISSUE THREAD

**Issue by Sa-kai** [ChosenArchitect/Project-Architect#45]
**Describe the bug**
->When player Morphs into Soul Vulture in overworld, I get set on fire, But if I Equip Blaze Heart from Trinkets, I don't take anymore fire damage and getting my self on fire, But if i were to wear Helmet, that Helmet would take damage overtime.

**To Reproduce**
1. Morph into Soul Vulture in Overworld
2. Equip Helmet and Blaze Heart Trinket
3. Expose yourself to direct sunlight
4. Notice Durability on helmet dropping

**Expected behavior**
->For Helmet not take any Damage while in morph state of a creature that would take fire damage in Overwold when having equipted Blaze Heart trinket

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2022-02-05_16 13 01](https://user-images.githubusercontent.com/49068691/152647555-cf39e025-2a90-4819-8765-560135507ce2.png)
![2022-02-05_16 12 57](https://user-images.githubusercontent.com/49068691/152647558-a67c7091-4f29-48db-a2ad-ecd85710bc8b.png)

**Modpack version**
->Project Architect 1.1
**Java Version**
->Latests up to date
**Modpack Launcher Used**
->MultiMC
**Ram Allocated**
->9GB

**Additional context**
->

**Comment by ChosenArchitect** [comment]
This is intended. The same would happen if you were a blaze. The flight through morph comes at a cost.
