### ISSUE TITLE
Copper block being able to smelt in tinkers smeltery/foundry

### ISSUE THREAD

**Issue by ScorpioneOrzion** [ChosenArchitect/Project-Architect#46]
**Is your feature request related to a problem? Please describe.**
->If you look in the recipe book, you will not see a way to smelt copper blocks in the 2 multiblock structures.

**Describe the solution you'd like**
-> Add the 2 recipes. (For now, you have to smelt the copper ingots instead.)

**Describe alternatives you've considered**
-> None (should be simple to add)

**Additional context**
->
No foundry/smeltery recipes as you can see.
![image](https://user-images.githubusercontent.com/36512390/152653701-6b1f80c8-e569-4856-b753-b776d3ff0771.png)

**Comment by ChosenArchitect** [comment]
Fixed in next update
