### ISSUE TITLE
TerraForged

### ISSUE THREAD

**Issue by wackoman6789** [ChosenArchitect/Project-Architect#48]
I've never liked some of the randomness in terrain gen like rivers that go nowhere and just disappear. Or how you can have a desert right next to a winter biome or jungle it just doesn't really make sense. 

My solution to this is something like TerraForged it adds amazing terrain gen and you can choose to not use it when starting a new world. It should be fully compatible with all of the mods. Let me tell you some of the cool things about it:

- Rivers actually go somewhere (the ocean) and they start out as small creeks and build up to large rivers
- The terrain fits more seamlessly so you can have a flatlands gradually build up into a mountain.  

![image](https://user-images.githubusercontent.com/15916115/152659027-6623d2ba-e00a-471a-9159-26c395d18b87.png)
 ![image](https://user-images.githubusercontent.com/15916115/152659201-d5c0324c-2b87-4999-b7d8-96c72c662047.png)
![image](https://user-images.githubusercontent.com/15916115/152659206-51b49223-3923-4690-9c9d-189030b52f63.png)
![image](https://user-images.githubusercontent.com/15916115/152659209-0f9bf60a-504f-4537-ac93-47e610debbea.png)

**Comment by ChosenArchitect** [comment]
I personally am not a big fan of this world gen. If you want something like it in the modpack then you can always use realistic world gen when creating a new world.
