### ISSUE TITLE
Dinnerbone Spider bug.

### ISSUE THREAD

**Issue by JemerAlex** [ChosenArchitect/Project-Architect#5]
**Describe the bug**
->I just saw a spider with the property of the name Dinnerbone. I don't know how or why.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

![Minecraft_ 1 16 5 - Singleplayer 02-02-22 17_56_46](https://user-images.githubusercontent.com/58668282/152202526-8ef4e166-b160-4d78-aafc-9869b3fd3fa7.png)

**Modpack version**
->1.1
**Java Version**
->1.8.0_311
**Modpack Launcher Used**
->Minecraft
**Ram Allocated**
->12Gb

**Comment by NicolaKuehnert** [comment]
Probably a mod adding the chance to spawn this
https://minecraft.fandom.com/wiki/Easter_eggs#Upside-down_mobs

**Comment by ChosenArchitect** [comment]
Not really seeing an issue unless all spiders are like this.
