### ISSUE TITLE
Some mods say Incompatible

### ISSUE THREAD

**Issue by ghost** [ChosenArchitect/Project-Architect#51]
**Describe the bug**
->Some mods say "made for an older version of minecraft" 
even when i have 1.16.5 version

**To Reproduce**
1. loading the game
2. creating new world
3. opening data packs in world creation menu
4. some mods say "incompatible, made for old"

**Expected behavior**
-> otherwise the game would run normally

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2022-02-06 16_20_34-Greenshot](https://user-images.githubusercontent.com/99110418/152677521-c79c578e-37ae-42c1-be92-6846e05bee64.png)

**Modpack version**
-> 1.1
**Java Version**
-> 1.16.5
**Modpack Launcher Used**
-> CurseForge
**Ram Allocated**
-> 6GB

**Additional context**
->

**Comment by litPanda2129** [comment]
that is normal. the modpack will still work.

**Comment by litPanda2129** [comment]
I don't know why it is saying incompatible but all modpacks I have played have had incompatible mods or data packs

**Comment by ChosenArchitect** [comment]
Try redownloading the modpack and if you added things like optfine then I would recommend removing them. The datapacks are set up on launch per world from the mods installed. I haven't added any datapacks to the modpack.
