### ISSUE TITLE
Deepslate ore processing

### ISSUE THREAD

**Issue by ShyMaiden** [ChosenArchitect/Project-Architect#52]
As of v1.1, deepslate ores (I believe all of them) cannot be processed by modded means. You can use the vanilla ways, such as smelting it in a vanilla furnace. You can also smelt the metal ores in the tinkers smeltery, but this does not show up in JEI.
I'd love to be able to process them in the same ways as their regular counterparts. So if I can throw normal redstone ore in a pulverizer for example, I'd like to be able to do the same with the deepslate version.

**Comment by ChosenArchitect** [comment]
Fixed in next update
