### ISSUE TITLE
EMC values for Caves and Cliffs Backport items

### ISSUE THREAD

**Issue by wcomartin** [ChosenArchitect/Project-Architect#58]
**Is your feature request related to a problem? Please describe.**
-> 

Some of the items have EMC values and some that are related do not eg. Flowering Azalea has EMC but regular Azalea does not.

![image](https://user-images.githubusercontent.com/2801793/152849121-469731c6-fbcc-42bb-bfa7-2a1d8e0415c3.png)
![image](https://user-images.githubusercontent.com/2801793/152849142-14e9eb5b-2647-4cfd-b366-2c29a57182cc.png)

**Describe the solution you'd like**
-> 

Add EMC values to items that make sense: Azalea, Moss Carpet, and Dripleaf, there may be others I have not come across yet.

**Comment by ChosenArchitect** [comment]
Added EMC for a few of the items.
