### ISSUE TITLE
Idea for the mod Morph

### ISSUE THREAD

**Issue by JemerAlex** [ChosenArchitect/Project-Architect#6]
**Is your feature request related to a problem? Please describe.**
->With the mod Morph, we can't use an ability with modded mobs. For example, the raven, we can't fly.

**Describe the solution you'd like**
->Maybe if you can, modify the mod to be able to use skills

**Comment by ChosenArchitect** [comment]
I will definitely start on that.

**Comment by ChosenArchitect** [comment]
I had to manually add Alex mobs to morph
