### ISSUE TITLE
Ground x-ray

### ISSUE THREAD

**Issue by jojoseph05** [ChosenArchitect/Project-Architect#60]
**Describe the bug**
-> I am able to x-ray through the ground unless I look down directly 

**To Reproduce**
1. Look around and the ground will become see through; I am able to see through the ground into caves.

**Expected behavior**
-> I dont x-ray through the ground

**Screenshots**
https://user-images.githubusercontent.com/86937795/152864024-ddcad64a-1fff-4042-a0f8-de9781059890.png
https://user-images.githubusercontent.com/86937795/152864038-9f95cacf-53b6-4567-8d47-f34d0dfee822.png
https://user-images.githubusercontent.com/86937795/152864115-88898194-7841-4d18-9c2a-436e8822a737.png
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->1.1
**Java Version**
->1.18.1
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->8gb

**Additional context**
-> My game was normal until i started building my house and used framed stairs. Now its bugged out and I can x-ray through the ground unless I look directly down. 
-> Happened in 1.0 version, after updating and changing optifine version, still no fix. I used Optifine 1.16.5 G8 and G7.

**Comment by texhex99** [comment]
Try updating your graphics drivers. Might have something to do with that.

**Comment by jojoseph05** [comment]
> Try updating your graphics drivers. Might have something to do with that.

Have had drivers up to date

**Comment by texhex99** [comment]
Does this happen in every world you play in? Or just the world shown in the screenshots

**Comment by jojoseph05** [comment]
> Does this happen in every world you play in? Or just the world shown in the screenshots

This has started happening in another world too. I noticed it happens after a while of playing. In my other world the x-ray doesnt happen as significant as these but my nether portal lit up texture becomes invisible while a nearby river's water goes invisible.

**Comment by texhex99** [comment]
What are your optifine settings? Do you have Fast Render or Fast Math enabled?

**Comment by jojoseph05** [comment]
> What are your optifine settings? Do you have Fast Render or Fast Math enabled?

If that is in the "performance" section, then I do believe that I have those on just because the modpack seems to lower my fps without those.

**Comment by texhex99** [comment]
Try turning them off. Those settings give the rendering engine permission to skip some passes and make it overall faster. This can conflict with mods that have their own rendering methods.

**Comment by jojoseph05** [comment]
> Try turning them off. Those settings give the rendering engine permission to skip some passes and make it overall faster. This can conflict with mods that have their own rendering methods.

https://user-images.githubusercontent.com/86937795/152909826-6d940cdf-674e-4005-9eed-8a5693a31db7.png

Tried to turn those settings off and no fix. Also seems to be in a certain area which is a hill with my house on it

**Comment by jojoseph05** [comment]
> Try turning them off. Those settings give the rendering engine permission to skip some passes and make it overall faster. This can conflict with mods that have their own rendering methods.

https://user-images.githubusercontent.com/86937795/152910810-5ecbfad0-d676-458f-9e1b-41ddd20e77e6.png
https://user-images.githubusercontent.com/86937795/152910813-e7ecc834-58e9-4dea-b81b-1a60f4cde6f0.png
 
I may have figured it out. It seems like framed stairs might have been causing this issue.

**Comment by ChosenArchitect** [comment]
I cant reproduce this issue
