### ISSUE TITLE
cave centipede morph hit box sticks

### ISSUE THREAD

**Issue by irondragonmage** [ChosenArchitect/Project-Architect#61]
**Describe the bug**
-> morphing into the cave centipede and then changing from it will keep the rear end of centipede visual and hit box no matter what you morph into and you will take suffocation damage from one block spaces approximately 3 blocks behind you also logging out does not fix the problem

**To Reproduce**
1. kill cave centipede 
2. morph into centipede as you would
3. then morph into any other creature with a different hit box like your own character 
4. 

**Expected behavior**
-> not to take damage from blocks a few feet from me not in that morph.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->
**Java Version**
->
**Modpack Launcher Used**
->
**Ram Allocated**
->

**Additional context**
->

![2022-02-08_01 43 41](https://user-images.githubusercontent.com/24581077/152932925-c7e3959f-673b-441e-8260-390a3c6825d3.png)

**Comment by ChosenArchitect** [comment]
I will remove that morph
