### ISSUE TITLE
Cannot load Minecraft on clean install

### ISSUE THREAD

**Issue by UnoMartino** [ChosenArchitect/Project-Architect#62]
**Describe the bug**
-> Minecraft cannot load on clean install.

**To Reproduce**
1. Run the game

**Expected behavior**
-> Expected the game to load

**Modpack version**
-> v1.1
**Java Version**
-> jre-openjdk 17.0.1.u12-1
**Modpack Launcher Used**
-> multimc5
**Ram Allocated**
-> 8192 MB

Attached crash log
[crash-2022-02-08_11.56.17-fml.txt](https://github.com/ChosenArchitect/Project-Architect/files/8023165/crash-2022-02-08_11.56.17-fml.txt)

![ss_2022-02-08_12-21-09](https://user-images.githubusercontent.com/69631058/152977287-39261615-ee0f-4de5-ac1d-f7146a0ff35e.png)

**Comment by HalJordan** [comment]
Use a compatible Java version. Drop down to 1.8 for 1.16 packs.

**Comment by UnoMartino** [comment]
Thanks. Changed to Java 1.8 and it worked. 
I think it would be a good idea to put the compatible java version in the description of the pack since there are two.
