### ISSUE TITLE
Metal Barrels Crafting

### ISSUE THREAD

**Issue by BoneDisturbed1** [ChosenArchitect/Project-Architect#63]
**Describe the bug**
->Metal Barrels does not support Charm or Crumbs Barrels

**To Reproduce**
1. Make a barrel
2. Try to make a iron barrel
3. Fail cause you didn't change the recipe to a minecraft barrel
4. Start over

**Expected behavior**
->Crumbs or Charm Barrel should make an Iron/gold/whatever barrel, add them to the recipe or make minecraft barrel the default craft

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->
**Java Version**
->
**Modpack Launcher Used**
->
**Ram Allocated**
->

**Additional context**
->

**Comment by BoneDisturbed1** [comment]
I have no clue why it defaulted to that topic, but was suppose to be Metal Barrels

**Comment by ChosenArchitect** [comment]
So I was able to fix the full crafting issue but using the upgrades you click on them only works on some.
