### ISSUE TITLE
Only "Limestone (RAW)" is generated when there is others from 3 diferent mods

### ISSUE THREAD

**Issue by plinio-jrm** [ChosenArchitect/Project-Architect#67]
**Describe the bug**
The **Limestone (RAW)** (from Chisel mod) is the only limestone generated in the world.
Limestones blocks that is not present according to the mods:
- Architect's Palette
- Create
- Quark

**To Reproduce**
Navigate throught the world or change the texturepack to display only those limestone.

**Expected behavior**
A recipe for those would be easier as adding those to the terrain generation would be harder impov.

**Screenshots**
![image](https://user-images.githubusercontent.com/15266388/153326082-3b63020a-455c-4541-ab60-fa51f44b77a3.png)

**Modpack version**
Version 1.1

**Java Version**
java 15.0.1 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)

**Modpack Launcher Used**
CurseForge

**Ram Allocated**
7GB

**Comment by Winkiloves23** [comment]
![image](https://user-images.githubusercontent.com/98195983/154377831-f8dc16b1-f007-418c-b8e5-25fda81675ed.png)
there is some just have to find it

**Comment by plinio-jrm** [comment]
> ![image](https://user-images.githubusercontent.com/98195983/154377831-f8dc16b1-f007-418c-b8e5-25fda81675ed.png) there is some just have to find it

Hm. i haven't found one yet. May you share where you find it? What biome and height?

**Comment by ChosenArchitect** [comment]
All types are generating
