### ISSUE TITLE
Very high memory usage with new Refined Storage EMC Integration

### ISSUE THREAD

**Issue by JacobCallahan** [ChosenArchitect/Project-Architect#69]
After updating to 1.2, I added the new block to my RS setup and it initially worked great. However, over the course of the next ~10m of use, the game really started bogging down. This was most notable when using JEI to populate recipes, maybe because it had to pull multiple types of items at once. During these times, tick lag jumped to around 250-530ms per spike.

I think this is a great addition but is going to need some optimizations before it is usable.

**To Reproduce**
1. Craft the new emc interface for RS (blanking on name)
2. Connect it to RS with external storage interface
3. Use the crafting grid to make things

**Expected behavior**
Ideally the initial behavior before memory and cpu usage 

**Screenshots**
During freeze
![Screenshot from 2022-02-10 07-58-54](https://user-images.githubusercontent.com/6618303/153416492-cd457cb1-31e6-4204-aeb5-1fa628840e0d.png)

After closing minecraft
![Screenshot from 2022-02-10 08-05-47](https://user-images.githubusercontent.com/6618303/153416535-55c852c1-faa5-432e-994b-771f7dce0668.png)

**Modpack version**
1.2
**Java Version**
openjdk 11.0.14 2022-01-18
OpenJDK Runtime Environment 18.9 (build 11.0.14+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.14+9, mixed mode, sharing)
**Modpack Launcher Used**
ATLauncher
**Ram Allocated**
10G

**Comment by ChosenArchitect** [comment]
I have tested extensively and im not noticing any significant changes on my end.
