### ISSUE TITLE
Nerf/Reduce the amount of emc from emeralds.

### ISSUE THREAD

**Issue by gabzoz456** [ChosenArchitect/Project-Architect#7]
**Is your feature request related to a problem? Please describe.**
->Emeralds are super easy to get thanks to ProjectE for example you could give yourself 64 pumpkins and get 15 emeralds for that and at 2k EMC a pop its just a little bit much.

**Describe the solution you'd like**
->theres some trades that suggest that a diamond is equivalent to one emerald so my suggestion its to make em equal at the very least.

**Describe alternatives you've considered**
->Another solution would be to remove the EMC of the emeralds which is a bit extreme but it is an alternative.

**Mod Sugestions**
->Simply editing the EMC value should work.

**Additional context**
->Ive added a screenshot of the trade i mention above. love your content keep up the great work!!!
![diamond to emerald](https://user-images.githubusercontent.com/98916735/152232411-2b21af38-baf9-4d4d-8403-b7ac80d17ce0.jpg)

**Comment by ChosenArchitect** [comment]
So Thins is something that I wouldn't be able to fix without editing villagers and that that point I should just remove them. (I don't want to remove them) There will be much better ways of getting EMC later on and I feel like this is just one of those minor ways of getting EMC. This pack is more about building than how much EMC you have.
