### ISSUE TITLE
Splash potions going through blocks when thrown 

### ISSUE THREAD

**Issue by Winkiloves23** [ChosenArchitect/Project-Architect#72]
**Describe the bug**
->so when i am throwing a splash potion of weakness to cure my villager it just goes right through the blocks and him i tried it with fire resistant potions and it does the same thing but i get the eff from the potion but the i dont know if i did something specific for this to happen but i have relogged and closed the game and brought it back up and still have the same problem 

**To Reproduce**
1. throw the splash potion 
2. 
3. 
4. 

**Expected behavior**
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
https://gyazo.com/31a5efa60bc574fe360b02404d2622fe
**Modpack version**
->1.1
**Java Version**
->java 7 jdk 
**Modpack Launcher Used**
->cursed forge 
**Ram Allocated**
->7G

**Additional context**
->

**Comment by Winkiloves23** [comment]
i haven updated to 1.2 and still having that issue

**Comment by ChosenArchitect** [comment]
I am not able to replicate this issue. When I use a splash potion it works as intended.
