### ISSUE TITLE
Crashes before loading world 

### ISSUE THREAD

**Issue by Alliekat00** [ChosenArchitect/Project-Architect#74]
**Describe the bug**
-> says Minecraft has no memory due to a crash report from a storage mod and block mod 

**To Reproduce**
1.  Remove mods and add similar ones
2. 
3. 
4. 

**Expected behavior**
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->
**Java Version**
->
**Modpack Launcher Used**
->
**Ram Allocated**
->

**Additional context**
->

**Comment by davidk20155** [comment]
[crash-2022-02-19_09.41.50-client.txt](https://github.com/ChosenArchitect/Project-Architect/files/8102405/crash-2022-02-19_09.41.50-client.txt)

**Comment by ChosenArchitect** [comment]
If you changed the modpack I will not support this
