### ISSUE TITLE
Not sure if there's a bug

### ISSUE THREAD

**Issue by Deadlite93** [ChosenArchitect/Project-Architect#75]
The morph mod is supposed to include abilities for some of the things you can turn in to, and im not sure what all would be included, but i cant seem to get any of the morphs abilities to work.  i have the keybind for abilities set to 'k' and have it assigned to only be for that. not sure if this a bug or intentional so i put it here, sorry

**Comment by plinio-jrm** [comment]
Yes. It seems it is not working. I did test it with alot of mobs that i killed and morph into it. Nothing happen to any of them.

**Comment by ChosenArchitect** [comment]
I believe abilities are a WIP
