### ISSUE TITLE
Quartz Glass smelting no longer possible

### ISSUE THREAD

**Issue by Angelyques** [ChosenArchitect/Project-Architect#76]
It appears the EMC value for quartz glass was removed. When trying to smelt it, regardless of method used, it only makes silicon. This makes the item no longer available.

**Comment by ChosenArchitect** [comment]
![2022-02-14_16 29 46](https://user-images.githubusercontent.com/35053440/153957514-6a323b49-87e0-4987-832d-8507286098dd.png)
This is the new way of getting it but I will add an EMC value back to it!

**Comment by ChosenArchitect** [comment]
Fixed as I found out you can't get that item..
![2022-02-14_16 37 18](https://user-images.githubusercontent.com/35053440/153958361-8db7449e-85ea-460d-87ab-fb62d44e166e.png)
.

**Comment by Angelyques** [comment]
I was able to make it at first. I had been using quite a bit of it in my
base build, which is why I was so surprised I had no way of getting more.
