### ISSUE TITLE
EMC Values for Tinker repair kits

### ISSUE THREAD

**Issue by alemonplays** [ChosenArchitect/Project-Architect#8]
**Is your feature request related to a problem? Please describe.**
-> Since Tinkers repair kits are always made from one specific material and can't be improved, modified and mixed, you could put an emc value on the repairs kits since you are only skipping the crafting or melting/casting part.  

**Describe the solution you'd like**
-> The value could be the original cost of materials.
For example: 
Stone repair kit = 2 cobble = 2 EMC
Iron repair kit = 2 iron ingots = 512 emc.

**Comment by ChosenArchitect** [comment]
This is intended so you use the smeltery even if you have the items you still have to cast it out.
