### ISSUE TITLE
Sophisticated backpack doesnt show the full inv

### ISSUE THREAD

**Issue by Deadlite93** [ChosenArchitect/Project-Architect#80]
When i have the backpack in my inventory and open it it works fine, but when its in my baubles, it only shows 3 lines of inventory, even when fully upgraded. i unbound everything else from 'b' to see if it was a hotkey issue but it still happened even when it was only open backpack bound to it.

**Comment by ChosenArchitect** [comment]
I'm not able to replicate this issue.

**Comment by ChosenArchitect** [comment]
Maybe include screenshots.
