### ISSUE TITLE
Some Slabs don't have emc values 

### ISSUE THREAD

**Issue by wackoman6789** [ChosenArchitect/Project-Architect#81]
**Describe the bug**
-> Some slabs don't have emc values 

**To Reproduce**
1.  make slab
2.  try to emc slab
3.  can't emc slab 
4.  sad

**Modpack version**
-> 1.2
**Java Version**
->
**Modpack Launcher Used**
-> curseforge
**Ram Allocated**
-> 12GB

**Comment by ChosenArchitect** [comment]
Some slabs cant have EMC as the base EMC if the part used to build it is set to 1 meaning if it game you 6 slabs they would = .5 EMC and that's not an option.

**Comment by HalJordan** [comment]
What about making sure all slabs can be crafted back into full blocks?
