### ISSUE TITLE
Dominion Wand from Ars crashes the gam,e

### ISSUE THREAD

**Issue by Tacocat14** [ChosenArchitect/Project-Architect#82]
**Describe the bug**
When I try to use the dominion wand to increase my bookwyrm's range, the game crashes

**To Reproduce**
1. Crouch right click the Dominion Wand on a Bookwyrm Lectern

**Expected behavior**
Expected game not to crash

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
1.2
**Java Version**
Java 8
**Modpack Launcher Used**
GDlauncher
**Ram Allocated**
8192

**Comment by ChosenArchitect** [comment]
Mod was updated so it should be fixed
