### ISSUE TITLE
Transmutation search field crashes game

### ISSUE THREAD

**Issue by davehaertel** [ChosenArchitect/Project-Architect#83]
This is something that just started happening.

- Open transmutation table or tablet, same behavior on both
- Click into the search field
- Start typing.
     
At this point the game starts its slow death/crash, goes to "Not responding" to having to force close it.

Version is the latest available on the Curse Forge launcher, was recently updated but can't be sure this is what caused the problem.

Tried to submit crash report through the curse launcher but it fails.

Have created a new world to test and it does not happen there, so it appears to be related to this particular save.  Any idea what to do to resolve this issue?  Lots of work already done in this save, I'd hate to lose it all.

**Comment by davehaertel** [comment]
This is more of a narrative than it previously gave me.  

The game crashed whilst ticking memory connection
Error: java.lang.NullPointerException: Ticking memory connection
Exit Code: -805306369

**Comment by ChosenArchitect** [comment]
I need more then what this is telling me. I need a actual crash log located in your crash log folder.

**Comment by davehaertel** [comment]
Thanks Chosen, when I realized it wasn't happening with a new world, I just rolled back a previous backup and haven't had any problems since.  It'd be great to know what the issue was though, I'll attach all 3 of the crash logs I have.  


[crash-2022-02-12_17.56.48.zip](https://github.com/ChosenArchitect/Project-Architect/files/8101185/crash-2022-02-12_17.56.48.zip)

**Comment by frostbyte96** [comment]
If it helps, I have a problem that sounds exactly like this one. For me I found it only happens when I have 6 or more watch of flowing time active. Had 10 watches active once and opened the transmutation tablet and my game instantly froze. As soon as the watches are off the tablet works fine.
