### ISSUE TITLE
Crashes When on Loading screen

### ISSUE THREAD

**Issue by BorutoUzumaki9119** [ChosenArchitect/Project-Architect#84]
I Dont know the bug it crashes on the booting screen I am fairly new to modding so I dont know anything Kindly Help me.
[New Text Document.txt](https://github.com/ChosenArchitect/Project-Architect/files/8068912/New.Text.Document.txt)

**Comment by Nichham1** [comment]
I have a similar issue. The game loads but stops at a screen that says two mods failed to load whereas the below mods failed. If you need the full logs, I'll be more than happy to provide such. this was from multimc and I didn't save it 

```
Mod File: ProjectRed-1.16.5-4.11.0-illumination.jar
	Failure message: Failed to load mod
	Mod Version: 4.11.0
	Mod Issue URL: https://github.com/MrTJP/ProjectRed
	Exception message: java.lang.NoClassDefFoundError: Could not initialize class codechicken.microblock.MicroBlockGenerator$
```
	
	Mod File: CBMultipart-1.16.5-3.0.4.123-universal.jar
	Failure message: Failed to load mod
	Mod Version: 3.0.4.123
	Mod Issue URL: https://github.com/TheCBProject/ForgeMultipart
	Exception message: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @330a7373

**Comment by Nichham1** [comment]
I have a similar issue. The game loads but stops at a screen that says two mods failed to load whereas the below mods failed. If you need the full logs, I'll be more than happy to provide such. This was from multimc and I didn't save it 

Mod File: ProjectRed-1.16.5-4.11.0-illumination.jar
	Failure message: Failed to load mod
	Mod Version: 4.11.0
	Mod Issue URL: https://github.com/MrTJP/ProjectRed
	Exception message: java.lang.NoClassDefFoundError: Could not initialize class codechicken.microblock.MicroBlockGenerator$
	
	Mod File: CBMultipart-1.16.5-3.0.4.123-universal.jar
	Failure message: Failed to load mod
	Mod Version: 3.0.4.123
	Mod Issue URL: https://github.com/TheCBProject/ForgeMultipart
	Exception message: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @330a7373

**Comment by ChosenArchitect** [comment]
Sorry I dont support the TLAUNCHER

**Comment by Nichham1** [comment]
Figured it out, was running the wrong version of java.
