### ISSUE TITLE
Stops world loading

### ISSUE THREAD

**Issue by Steelbot2803** [ChosenArchitect/Project-Architect#86]
**Describe the bug**
-> The world loading stops and says "Error in currently selected data packs prevented the world from loading. You can either try to load it with only the vanilla data pack ("safe mode"), or go back to the title screen and fix it manually." I tried safe mode but it comes back to the same screen. Also I have no data packs in the folder.

**To Reproduce**
1. Click on play button of the world

**Expected behavior**
-> The world loads and I get to continue generating enormous amounts of EMC (evil laugh).

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image_2022-02-17_000351](https://user-images.githubusercontent.com/66138423/154332576-b0e02644-fc11-44e5-a595-b4e15ecd7762.png)
![image](https://user-images.githubusercontent.com/66138423/154333344-63569056-b4be-4dcd-bfce-1fdd12165392.png)

**Modpack version**
-> 1.4
**Java Version**
-> 1.16.5
**Modpack Launcher Used**
-> Curseforge
**Ram Allocated**
-> 10 GB

**Additional context**
-> The world was last saved in modpack version 1.3.

**Comment by ChosenArchitect** [comment]
I have no idea what I am looking at... So datapacks are saved in your saves folder and are generated on world load. I haven't added any datapacks... The ones that are generated are added the mods. I have no idea what the issue is here.
