### ISSUE TITLE
Morph mod Bug 

### ISSUE THREAD

**Issue by Winkiloves23** [ChosenArchitect/Project-Architect#87]
**Describe the bug**
->When i turned into a (Bone Serpent) and change into something else the tail didn't go away the tail would go into block and make me take dmg from suffocation

**To Reproduce**
1. Change into a bone serpent then change to something else
2. 
3. 
4. 

**Expected behavior**
-> complexly changing back into the mob 

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image](https://user-images.githubusercontent.com/98195983/154344779-95128f37-6d29-4127-8495-e98f0a8e0ef4.png)

**Modpack version**
->1.4
**Java Version**
->jre-8u321 windows x64
**Modpack Launcher Used**
->Cursedforge 
**Ram Allocated**
->7G

**Additional context**
-> I did try to log out and in to see if it would go away but didn't work then i tried to to turn back into the Bone Serpent to see if that would work but nope just gave me a 2nd tail i then used my Advance dislocator to teleport me back home That finally got the tails to disappear

**Comment by ChosenArchitect** [comment]
Blocked that morph
