### ISSUE TITLE
Game Crashes on Launch

### ISSUE THREAD

**Issue by JaffaCakeRGB** [ChosenArchitect/Project-Architect#88]
When attempting to launch the game, the game crashes.

1. Open launcher via CurseForge
2. Press Play
3. Crash

**Screenshots**

**Modpack version**
1.4

**Ram Allocated**
20 GB
![Uploading Desktop Screenshot 2022.02.16 - 15.02.12.84.png…]()
[latest.log](https://github.com/ChosenArchitect/Project-Architect/files/8083545/latest.log)

**Comment by Winkiloves23** [comment]
update your java or something or use jarfix to fix your java that might help or your missing some files so might have to redownload
