### ISSUE TITLE
Morph Mod External Limb Bug

### ISSUE THREAD

**Issue by CallumJohnson** [ChosenArchitect/Project-Architect#89]
**Describe the bug**
-> When morphing into any creature with 3D external limbs, such as the Bone Serpent or the Cave Centipede, the external limbs stay when morphing into any other creature.

EDIT: To fix this bug, the player needs to die. Upon respawning, the tail is gone.

**To Reproduce**
1. Kill Cave Centipede, unlocking its morph.
2. Morph into Cave Centipede
3. Morph into anything else 
4. Take damage from external limbs passing into blocks.

**Expected behavior**
-> Once you morph out of the centipede morph, its expected to not be half-man, half-centipede.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2022-02-16_21 28 02](https://user-images.githubusercontent.com/74352969/154360681-1f4bd0c7-50cf-4b2b-bd1c-f4c1331d74c4.png)
![2022-02-16_21 28 44](https://user-images.githubusercontent.com/74352969/154360688-b27e39aa-c694-4e04-bdb3-d073df0e1e1a.png)

**Modpack version**
-> 1.4
**Java Version**
-> OpenJDK version "1.8.0_292"
**Modpack Launcher Used**
-> CurseForge Official
**Ram Allocated**
-> 16GB (JVM Argument: 16384m)

**Additional context**
-> I believe another user has posted about this, but I felt like noting that it isn't an isolated model issue could be important :)

**Comment by Winkiloves23** [comment]
its the same as the bone serpent you have to teleport away to get rid of it

**Comment by ChosenArchitect** [comment]
Blocked that morph
