### ISSUE TITLE
Crashes When I Fall Below The Bee Dimension As A Bee

### ISSUE THREAD

**Issue by DeDog103** [ChosenArchitect/Project-Architect#90]
**Describe the bug**
->When I am morphed as a bee and leave the bee dimension, the game crashes

**To Reproduce**
1. Kill a bee
2. Morph into the bee
3. Enter the bee dimension
4. Leave the bee dimension

**Expected behavior**
->leave the bee dimension

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->v1.4
**Java Version**
->N/A
**Modpack Launcher Used**
->Curse Forge
**Ram Allocated**
->8 GB

**Additional context**
->

**Comment by ChosenArchitect** [comment]
Removed the Mod as it doesn't add much to the modapck and has a lot of issue with getting back and forth from the Dimension.
