### ISSUE TITLE
Upgraded Backpack have UI bigger than screen

### ISSUE THREAD

**Issue by plinio-jrm** [ChosenArchitect/Project-Architect#91]
**Describe the bug**
Upgrade the backpack to Gold or better. When opening the backpack, the UI turn out to be larget than Minecraft window.
> I think #80 is related, but not sure.

**To Reproduce**
1. Upgrade Backpack to `Gold Packpack`.
2. Open `Gold Backpack` inventory.

**Expected behavior**
Or increase the number of rows and limit the number of lines, Or add a scrollbar to limit oversize UI.
I know i can decrease the UI Scale, but it becomes dificult to read and see informations on screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/15266388/154373017-2bfbd307-6abf-4c14-9655-584beadc963f.png)

**Modpack version**
->1.4

**Java Version**
> java 15.0.1 2020-10-20
> Java(TM) SE Runtime Environment (build 15.0.1+9-18)
> Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)

**Modpack Launcher Used**
->MultiMC

**Ram Allocated**
->7GB

**Comment by Winkiloves23** [comment]
you have to change your gui scale thats not a bug it has always been like that set it to 3
