### ISSUE TITLE
resonant ender Bugged

### ISSUE THREAD

**Issue by Winkiloves23** [ChosenArchitect/Project-Architect#92]
**Describe the bug**
->Cant place Resonant ender on the ground 

**To Reproduce**
1. Make resonant ender
2. put it in a bucket 
3. try to put resonant ender onto the ground 
4. 

**Expected behavior**
->to be able to place it down onto the ground to cooldown my reactor 

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->1.4
**Java Version**
->Jre-8u321-windows-x64
**Modpack Launcher Used**
->cursedforge 
**Ram Allocated**
->7G

**Additional context**
->

**Comment by ChosenArchitect** [comment]
Some fluids in 1.16 don't have a placable version and this is a example of that.
