### ISSUE TITLE
Unplayable Lag in Brimstone Cavern Biome (Nether)

### ISSUE THREAD

**Issue by Kylar1014** [ChosenArchitect/Project-Architect#93]
**Describe the bug**
Upon venturing into the nether, I saw a brimstone biome and went to explore. I love the green flames. After being in the Biome for a few minutes collecting materials, I noticed block lag while trying to mine cobalt. A few minutes later, I tried to eat and couldn't. Then I was on fire from something but due to the lag I have no clue where it came from.
->

**To Reproduce**
1. I left the biome and the lag went away.
2. I went back into the biome and the lag came back,
3. I tested this twice.
4. 

**Expected behavior**
->I wouldn't expect to get this kind of lag in a singleplayer world. This is what you typically see when too many players are playing on a server at once.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
 -> I took (F3)  screenshots in the biome with lag and without.
**Modpack version**
-> 1.4
**Java Version**
-> 1.8
**Modpack Launcher Used**
-> Curseforge
**Ram Allocated**
-> 8GB

**Additional context**
->
![F3_With_Lag](https://user-images.githubusercontent.com/49353787/154392799-ff696e1d-06cc-48a2-8c74-088b4c5ce5c8.png)
![F3_Without_Lag](https://user-images.githubusercontent.com/49353787/154392812-2766f980-30d0-4f85-8e73-c31b16a4c03b.png)

**Comment by ChosenArchitect** [comment]
Tested and see no issue. Looking at your screenshots you are getting 64fps in both of them.

**Comment by Kylar1014** [comment]
The tick lag was significant different in the two screenshots. The one with
lag had over 7000ms tic speed. FPS means nothing if you cannot play the
game.
