### ISSUE TITLE
Sugesstion Delete mod(s)

### ISSUE THREAD

**Issue by gamingoninsulin** [ChosenArchitect/Project-Architect#97]
**Is your feature request related to a problem? Please describe.**
->
there is a messgae that xaero world map is out dated and there a 2 diffrent maps on screen when log in from a fresh copy of project architect

**Describe the solution you'd like**
->
delete Xaerio world and mini map

**Describe alternatives you've considered**
->  becuase the ftb Chunks if better and has more thing you can do such as claim land

**Mod Sugestions**
-> is already in the pack

**Comment by ChosenArchitect** [comment]
There is a reason they are both in the pack. Ftbs map is a side effect of FTBs Chunk claiming mod. Xaerio is a much better map mod. All you have to do is go into the settings and Disable the FTB mini-map. It's like that for a reason.
